In [66]:
%logstop
%logstart -rtq ~/.logs/dw.py append
%matplotlib inline
import matplotlib
import seaborn as sns
sns.set()
matplotlib.rcParams['figure.dpi'] = 144

In [67]:
from static_grader import grader

# DW Miniproject
## Introduction

The objective of this miniproject is to exercise your ability to wrangle tabular data set and aggregate large data sets into meaningful summary statistics. We'll work with the same medical data used in the `pw` miniproject but leverage the power of Pandas to more efficiently represent and act on our data.

## Downloading the data

We first need to download the data we'll be using from Amazon S3:

In [68]:
# !mkdir dw-data
# !wget http://dataincubator-wqu.s3.amazonaws.com/dwdata/201701scripts_sample.csv.gz -nc -P ./dw-data/
# !wget http://dataincubator-wqu.s3.amazonaws.com/dwdata/201606scripts_sample.csv.gz -nc -P ./dw-data/
# !wget http://dataincubator-wqu.s3.amazonaws.com/dwdata/practices.csv.gz -nc -P ./dw-data/
# !wget http://dataincubator-wqu.s3.amazonaws.com/dwdata/chem.csv.gz -nc -P ./dw-data/

## Loading the data

Similar to the `PW` miniproject, the first step is to read in the data. The data files are stored as compressed CSV files. You can load the data into a Pandas DataFrame by making use of the `gzip` package to decompress the files and Panda's `read_csv` methods to parse the data into a DataFrame. You may want to check the Pandas documentation for parsing [CSV](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) files for reference.

For a description of the data set please, refer to the [PW miniproject](./pw.ipynb). **Note that all questions make use of the 2017 data only, except for Question 5 which makes use of both the 2017 and 2016 data.**

In [69]:
import pandas as pd
import numpy as np
import gzip

In [70]:
# load the 2017 data
scripts = pd.read_csv('./dw-data/201701scripts_sample.csv.gz', compression='gzip')
scripts.head()

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity
0,N85639,0106020C0,Bisacodyl_Tab E/C 5mg,1,0.39,0.47,12
1,N85639,0106040M0,Movicol Plain_Paed Pdr Sach 6.9g,1,4.38,4.07,30
2,N85639,0301011R0,Salbutamol_Inha 100mcg (200 D) CFF,1,1.50,1.40,1
3,N85639,0304010G0,Chlorphenamine Mal_Oral Soln 2mg/5ml,1,2.62,2.44,150
4,N85639,0401020K0,Diazepam_Tab 2mg,1,0.16,0.26,6

In [71]:
col_names=[ 'code', 'name', 'addr_1', 'addr_2', 'borough', 'village', 'post_code']
practices = pd.read_csv('./dw-data/practices.csv.gz', names = col_names)
practices.head()

,code,name,addr_1,addr_2,borough,village,post_code
0,A81001,THE DENSHAM SURGERY,THE HEALTH CENTRE,LAWSON STREET,STOCKTON ON TEES,CLEVELAND,TS18 1HU
1,A81002,QUEENS PARK MEDICAL CENTRE,QUEENS PARK MEDICAL CTR,FARRER STREET,STOCKTON ON TEES,CLEVELAND,TS18 2AW
2,A81003,VICTORIA MEDICAL PRACTICE,THE HEALTH CENTRE,VICTORIA ROAD,HARTLEPOOL,CLEVELAND,TS26 8DB
3,A81004,WOODLANDS ROAD SURGERY,6 WOODLANDS ROAD,NaN,MIDDLESBROUGH,CLEVELAND,TS1 3BE
4,A81005,SPRINGWOOD SURGERY,SPRINGWOOD SURGERY,RECTORY LANE,GUISBOROUGH,NaN,TS14 7DJ

In [72]:
chem = pd.read_csv('./dw-data/chem.csv.gz', compression = 'gzip')
chem.head()

    CHEM SUB                                NAME
0  0101010A0                     Alexitol Sodium
1  0101010B0                          Almasilate
2  0101010C0                 Aluminium Hydroxide
3  0101010D0  Aluminium Hydroxide With Magnesium
4  0101010E0                        Hydrotalcite

Now that we've loaded in the data, let's first replicate our results from the `PW` miniproject. Note that we are now working with a larger data set so the answers will be different than in the `PW` miniproject even if the analysis is the same.

## Question 1: summary_statistics

In the `PW` miniproject we first calculated the total, mean, standard deviation, and quartile statistics of the `'items'`, `'quantity'`', `'nic'`, and `'act_cost'` fields. To do this we had to write some functions to calculate the statistics and apply the functions to our data structure. The DataFrame has a `describe` method that will calculate most (not all) of these things for us.

Submit the summary statistics to the grader as a list of tuples: [('act_cost', (total, mean, std, q25, median, q75)), ...]

In [21]:
des = scripts.describe()

In [23]:
des

               items            nic       act_cost       quantity
count  973193.000000  973193.000000  973193.000000  973193.000000
mean        9.133136      73.058915      67.986613     741.329835
std        29.204198     188.070257     174.401703    3665.426958
min         1.000000       0.000000       0.040000       0.000000
25%         1.000000       7.800000       7.330000      28.000000
50%         2.000000      22.640000      21.220000     100.000000
75%         6.000000      65.000000      60.670000     350.000000
max      2384.000000   16320.000000   15108.320000  577720.000000

In [30]:
des.columns

'items'

In [34]:
[('items', tuple([des['items']['count']] + [des['items']['mean']] + [des['items']['std']] +
 [des['items']['25%']] + [des['items']['50%']]+ [des['items']['75%']]))]

[('items', (973193.0, 9.133135976111625, 29.204198282803603, 1.0, 2.0, 6.0))]

In [77]:
# solution1
summary_stats = []
for i in ['items', 'quantity', 'nic', 'act_cost']:
    summary_stats.append(
        (str(i), tuple([sum (scripts[i])] + [des[i]['mean']] + [des[i]['std']] +
 [des[i]['25%']] + [des[i]['50%']]+ [des[i]['75%']]))
    )

In [78]:
summary_stats

[('items', (8888304, 9.133135976111625, 29.204198282803603, 1.0, 2.0, 6.0)),
 ('quantity',
  (721457006, 741.3298348837282, 3665.426958467915, 28.0, 100.0, 350.0)),
 ('nic',
  (71100424.84000827, 73.05891517920908, 188.070256906825, 7.8, 22.64, 65.0)),
 ('act_cost',
  (66164096.11999956,
   67.98661326170655,
   174.40170332301963,
   7.33,
   21.22,
   60.67))]

In [71]:
# solution2
import statistics as st
# sum(scripts['items'])
summary_stats = []
for i in ['items', 'quantity', 'nic', 'act_cost']:
    summary_stats.append(
        (str(i), tuple([des[i]['count'] * des[i]['mean']] + [des[i]['mean']] + [des[i]['std']] +
 [des[i]['25%']] + [st.median(scripts[i])]+ [des[i]['75%']]))
    )

In [72]:
summary_stats

[('items', (8888304.0, 9.133135976111625, 29.204198282803603, 1.0, 2, 6.0)),
 ('quantity',
  (721457006.0, 741.3298348837282, 3665.426958467915, 28.0, 100, 350.0)),
 ('nic',
  (71100424.84000002, 73.05891517920908, 188.070256906825, 7.8, 22.64, 65.0)),
 ('act_cost',
  (66164096.11999998,
   67.98661326170655,
   174.40170332301963,
   7.33,
   21.22,
   60.67))]

In [ ]:
summary_stats = [('items', (0,) * 6), ('quantity', (0,) * 6), ('nic', (0,) * 6), ('act_cost', (0,) * 6)]

In [79]:
grader.score.dw__summary_statistics(summary_stats)

==================
Your score:  1.0
==================

## Question 2: most_common_item

We can also easily compute summary statistics on groups within the data. In the `pw` miniproject we had to explicitly construct the groups based on the values of a particular field. Pandas will handle that for us via the `groupby` method. This process is [detailed in the Pandas documentation](https://pandas.pydata.org/pandas-docs/stable/groupby.html).

Use `groupby` to calculate the total number of items dispensed for each `'bnf_name'`. Find the item with the highest total and return the result as `[(bnf_name, total)]`.

In [97]:
scripts.groupby('bnf_name').agg({'items': ['sum']}).reset_index().sort_values(('items', 'sum')).tail()

                      bnf_name   items
                                   sum
652         Amlodipine_Tab 5mg  128245
11298     Simvastatin_Tab 40mg  132941
924    Aspirin Disper_Tab 75mg  148591
9460         Paracet_Tab 500mg  151669
9033   Omeprazole_Cap E/C 20mg  218583

In [98]:
most_common_item = [("Omeprazole_Cap E/C 20mg", 218583)]

In [99]:
grader.score.dw__most_common_item(most_common_item)

==================
Your score:  1.0
==================

## Question 3: items_by_region

Now let's find the most common item by post code. The post code information is in the `practices` DataFrame, and we'll need to `merge` it into the `scripts` DataFrame. Pandas provides [extensive documentation](https://pandas.pydata.org/pandas-docs/stable/merging.html) with diagrammed examples on different methods and approaches for joining data. The `merge` method is only one of many possible options.

Return your results as a list of tuples `(post code, item name, amount dispensed as % of total)`. Sort your results ascending alphabetically by post code and take only results from the first 100 post codes.

**NOTE:** Some practices have multiple postal codes associated with them. Use the alphabetically first postal code. Note some postal codes may have multiple `'bnf_name'` with the same prescription rate for the maximum. In this case, take the alphabetically first `'bnf_name'` (as in the PW miniproject).

In [12]:
practices.head()

,code,name,addr_1,addr_2,borough,village,post_code
0,A81001,THE DENSHAM SURGERY,THE HEALTH CENTRE,LAWSON STREET,STOCKTON ON TEES,CLEVELAND,TS18 1HU
1,A81002,QUEENS PARK MEDICAL CENTRE,QUEENS PARK MEDICAL CTR,FARRER STREET,STOCKTON ON TEES,CLEVELAND,TS18 2AW
2,A81003,VICTORIA MEDICAL PRACTICE,THE HEALTH CENTRE,VICTORIA ROAD,HARTLEPOOL,CLEVELAND,TS26 8DB
3,A81004,WOODLANDS ROAD SURGERY,6 WOODLANDS ROAD,NaN,MIDDLESBROUGH,CLEVELAND,TS1 3BE
4,A81005,SPRINGWOOD SURGERY,SPRINGWOOD SURGERY,RECTORY LANE,GUISBOROUGH,NaN,TS14 7DJ

In [13]:
scripts.head()

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity
0,N85639,0106020C0,Bisacodyl_Tab E/C 5mg,1,0.39,0.47,12
1,N85639,0106040M0,Movicol Plain_Paed Pdr Sach 6.9g,1,4.38,4.07,30
2,N85639,0301011R0,Salbutamol_Inha 100mcg (200 D) CFF,1,1.50,1.40,1
3,N85639,0304010G0,Chlorphenamine Mal_Oral Soln 2mg/5ml,1,2.62,2.44,150
4,N85639,0401020K0,Diazepam_Tab 2mg,1,0.16,0.26,6

In [14]:
merged_pdf = practices.merge(scripts, left_on = 'code', right_on = 'practice', how = 'inner')

In [103]:
merged_pdf.head()

,code,name,addr_1,addr_2,borough,village,post_code,practice,bnf_code,bnf_name,items,nic,act_cost,quantity
0,A81005,SPRINGWOOD SURGERY,SPRINGWOOD SURGERY,RECTORY LANE,GUISBOROUGH,NaN,TS14 7DJ,A81005,0101010G0,Maalox_Susp 195mg/220mg/5ml S/F,1,3.35,3.11,500
1,A81005,SPRINGWOOD SURGERY,SPRINGWOOD SURGERY,RECTORY LANE,GUISBOROUGH,NaN,TS14 7DJ,A81005,0101010G0,Mucogel_Susp 195mg/220mg/5ml S/F,1,5.98,5.55,1000
2,A81005,SPRINGWOOD SURGERY,SPRINGWOOD SURGERY,RECTORY LANE,GUISBOROUGH,NaN,TS14 7DJ,A81005,0101010L0,Maalox Plus_Susp S/F,1,3.90,3.62,500
3,A81005,SPRINGWOOD SURGERY,SPRINGWOOD SURGERY,RECTORY LANE,GUISBOROUGH,NaN,TS14 7DJ,A81005,0101021B0,Alginate_Raft-Forming Oral Susp S/F,6,14.12,13.16,2000
4,A81005,SPRINGWOOD SURGERY,SPRINGWOOD SURGERY,RECTORY LANE,GUISBOROUGH,NaN,TS14 7DJ,A81005,0101021B0,Sod Algin/Pot Bicarb_Susp S/F,6,35.84,33.24,3500

In [15]:
gpdf = merged_pdf.groupby(['post_code','bnf_name']).agg({'items':['sum']}).reset_index()

In [16]:
# gpdf['all'] =
df2 = merged_pdf.groupby(['post_code']).agg({'items':['sum']})[('items', 'sum')]

In [17]:
gpdfm = gpdf.merge(df2, left_on = 'post_code', right_on = 'post_code', how  ='inner')

In [18]:
gpdfm['perct'] = gpdfm[('items_x', 'sum')] / gpdfm[('items_y', 'sum')]

In [22]:
gpdfm.head(2)

,post_code,bnf_name,items_x,items_y,perct
,,,sum,sum,
0,B11 4BW,3m Health Care_Cavilon Durable Barrier C,7,22731,0.000308
1,B11 4BW,3m Health Care_Cavilon No Sting Barrier,2,22731,0.000088

In [33]:
gpdfm.groupby('post_code').agg({('perct','bnf_name'): ['max']})

KeyError: "Column '('perct', 'bnf_name')' does not exist!"

In [27]:
dir(gpdfm.groupby('post_code'))

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_accessors',
 '_add_numeric_operations',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_aggregate',
 '_aggregate_generic',
 '_aggregate_item_by_item',
 '_aggregate_multiple_funcs',
 '_apply_filter',
 '_apply_to_column_groupbys',
 '_apply_whitelist',
 '_assure_grouper',
 '_block_agg_axis',
 '_bool_agg',
 '_builtin_table',
 '_choose_path',
 '_concat_objects',
 '_constructor',
 '_cumcount_array',
 '_cython_agg_blocks',
 '_cython_agg_general',
 '_cython_table',
 '_cython_transform',
 '_decide_output_index',
 '_def_str',
 '_define_paths',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_fill',
 '_get_cythonized_result',
 '_get_data_to_aggregate',
 '_get_index',
 '_get_indices',
 '_gotitem',
 '_group_selection',
 '_insert_inaxis_grouper_inplace',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cython_func',
 '_iterate_column_groupbys',
 '_iterate_slices',
 '_make_wrapper',
 '_obj_with_exclusions',
 '_python_agg_general',
 '_python_apply_general',
 '_reindex_output',
 '_reset_cache',
 '_reset_group_selection',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_set_group_selection',
 '_set_result_index_ordered',
 '_shallow_copy',
 '_transform_fast',
 '_transform_general',
 '_transform_item_by_item',
 '_transform_should_cast',
 '_try_aggregate_string_function',
 '_try_cast',
 '_wrap_agged_blocks',
 '_wrap_aggregated_output',
 '_wrap_applied_output',
 '_wrap_generic_output',
 '_wrap_transformed_output',
 'agg',
 'aggregate',
 'all',
 'any',
 'apply',
 'backfill',
 'bfill',
 'bnf_name',
 'boxplot',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cumcount',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'dtypes',
 'expanding',
 'ffill',
 'fillna',
 'filter',
 'first',
 'get_group',
 'groups',
 'head',
 'hist',
 'idxmax',
 'idxmin',
 'indices',
 'items_x',
 'items_y',
 'last',
 'mad',
 'max',
 'mean',
 'median',
 'min',
 'ndim',
 'ngroup',
 'ngroups',
 'nth',
 'nunique',
 'ohlc',
 'pad',
 'pct_change',
 'perct',
 'pipe',
 'plot',
 'post_code',
 'prod',
 'quantile',
 'rank',
 'resample',
 'rolling',
 'sem',
 'shift',
 'size',
 'skew',
 'std',
 'sum',
 'tail',
 'take',
 'transform',
 'tshift',
 'var']

In [66]:
final_df = gpdfm.sort_values(['perct','bnf_name'],ascending=False).groupby('post_code').head(1).sort_values('post_code').head(100)

In [67]:
final_df  = final_df[['post_code', 'bnf_name', 'perct']]

In [68]:
# final_df[1:].to_dict()
for i in range (10):
    
    print (final_df.iloc[i][0])

B11 4BW
B12 9LP
B18 7AL
B21 9RY
B23 6DJ
B26 1TH
B61 0AZ
B70 7AW
B72 1RL
B8 1RZ

In [69]:
items_by_region = []
for row in range (100):
    items_by_region.append ((final_df.iloc[row][0], final_df.iloc[row][1], final_df.iloc[row][2]))

In [70]:
items_by_region

[('B11 4BW', 'Salbutamol_Inha 100mcg (200 D) CFF', 0.031058906339360346),
 ('B12 9LP', 'Paracet_Tab 500mg', 0.024014460320192804),
 ('B18 7AL', 'Salbutamol_Inha 100mcg (200 D) CFF', 0.027111371172225472),
 ('B21 9RY', 'Metformin HCl_Tab 500mg', 0.03329358300834757),
 ('B23 6DJ', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.021384456106529576),
 ('B26 1TH', 'Sterimar Isotonic Nsl Spy 50ml', 0.16666666666666666),
 ('B61 0AZ', 'Omeprazole_Cap E/C 20mg', 0.028713318284424378),
 ('B70 7AW', 'Paracet_Tab 500mg', 0.025135992162726547),
 ('B72 1RL', 'Omeprazole_Cap E/C 20mg', 0.020228765092141495),
 ('B8 1RZ', 'Metformin HCl_Tab 500mg', 0.021347750961484866),
 ('B9 5PU', 'Ventolin_Evohaler 100mcg (200 D)', 0.024826024522257815),
 ('B90 3LX', 'Omeprazole_Cap E/C 20mg', 0.026965103983080718),
 ('BA5 1XJ', 'Omeprazole_Cap E/C 20mg', 0.028261290947858113),
 ('BB11 2DL', 'Omeprazole_Cap E/C 20mg', 0.02782563103887349),
 ('BB12 8BS', 'Amoxicillin_Cap 500mg', 0.08424908424908426),
 ('BB2 1AX', 'Omeprazole_Cap E/C 20mg', 0.03428191046763188),
 ('BB3 1PY', 'Omeprazole_Cap E/C 20mg', 0.032683395995453356),
 ('BB4 5SL', 'Omeprazole_Cap E/C 20mg', 0.03747689029549087),
 ('BB4 7PL', 'Omeprazole_Cap E/C 20mg', 0.027477496877557173),
 ('BB7 2JG', 'Omeprazole_Cap E/C 20mg', 0.027980664806967485),
 ('BB8 0JZ', 'Omeprazole_Cap E/C 20mg', 0.022056235579367253),
 ('BB9 7SR', 'Omeprazole_Cap E/C 20mg', 0.02247662283190644),
 ('BD16 4RP', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.022780283004198414),
 ('BD19 5AP', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.02066220372715759),
 ('BD3 8QH', 'Atorvastatin_Tab 40mg', 0.031662850096882154),
 ('BD4 7SS', 'Atorvastatin_Tab 40mg', 0.033709213051823415),
 ('BH14 0DJ', 'Omeprazole_Cap E/C 20mg', 0.03024583064999667),
 ('BH14 9ET', 'Omeprazole_Cap E/C 20mg', 0.02447027939246203),
 ('BH18 8EE', 'Omeprazole_Cap E/C 20mg', 0.027092370049064923),
 ('BH23 3AF', 'Omeprazole_Cap E/C 20mg', 0.03546099290780142),
 ('BL1 3RG', 'Omeprazole_Cap E/C 20mg', 0.03362566656383588),
 ('BL1 8TU', 'Omeprazole_Cap E/C 20mg', 0.027729220222793487),
 ('BL2 6NT', 'Omeprazole_Cap E/C 20mg', 0.027192463911824716),
 ('BL3 5HP', 'Omeprazole_Cap E/C 20mg', 0.03129933420275929),
 ('BL9 0NJ', 'Omeprazole_Cap E/C 20mg', 0.03351587656003949),
 ('BL9 0SN', 'Omeprazole_Cap E/C 20mg', 0.030791674554829226),
 ('BN1 6AG', 'Lansoprazole_Cap 15mg (E/C Gran)', 0.021755523716160168),
 ('BN1 8DD', 'Aspirin Disper_Tab 75mg', 0.021517850460294887),
 ('BN9 9PW', 'Omeprazole_Cap E/C 20mg', 0.01855317763853853),
 ('BR2 9GT', 'Influenza_Vac Inact 0.5ml Pfs', 0.04301700334253742),
 ('BR3 3FD', 'Omeprazole_Cap E/C 20mg', 0.02865911645197545),
 ('BS16 3TD', 'Omeprazole_Cap E/C 20mg', 0.03752737892431249),
 ('BS23 3HQ', 'Omeprazole_Cap E/C 20mg', 0.03210555434472815),
 ('BS4 1WH', 'Omeprazole_Cap E/C 20mg', 0.029600778967867575),
 ('BS4 4HU', 'Omeprazole_Cap E/C 20mg', 0.037361354349095155),
 ('BS48 2XX', 'Omeprazole_Cap E/C 20mg', 0.03059550404914828),
 ('BS48 3HA', 'Omeprazole_Cap E/C 20mg', 0.029018811457887986),
 ('CA11 8HW', 'Omeprazole_Cap E/C 20mg', 0.028185232426303854),
 ('CB22 3HU', 'Omeprazole_Cap E/C 20mg', 0.03785659530197667),
 ('CB9 8HF', 'Omeprazole_Cap E/C 20mg', 0.03391110538046382),
 ('CH1 4DS', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.0257736189772634),
 ('CH41 8DB', 'Omeprazole_Cap E/C 20mg', 0.03440588294013909),
 ('CH44 5UF', 'Omeprazole_Cap E/C 20mg', 0.03329780587305671),
 ('CH62 5HS', 'Omeprazole_Cap E/C 20mg', 0.03800369432852158),
 ('CH62 6EE', 'Influenza_Vac Inact 0.5ml Pfs', 0.057585894269547),
 ('CH65 6TG', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.026067517902474142),
 ('CH66 3PB', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.03100619319552803),
 ('CM18 6LY', 'Omeprazole_Cap E/C 20mg', 0.026445315758738635),
 ('CR0 0JA', 'Salbutamol_Inha 100mcg (200 D) CFF', 0.0229302033116747),
 ('CT11 8AD', 'Omeprazole_Cap E/C 20mg', 0.022307039864291774),
 ('CV1 4FS', 'Omeprazole_Cap E/C 20mg', 0.028455180531743392),
 ('CV12 8NQ', 'Omeprazole_Cap E/C 20mg', 0.025301518438177874),
 ('CV21 2DN', 'Omeprazole_Cap E/C 20mg', 0.04102890311294875),
 ('CV6 2FL', 'Omeprazole_Cap E/C 20mg', 0.036250663502669624),
 ('CV6 6DR', 'Omeprazole_Cap E/C 20mg', 0.030544721504009817),
 ('CW1 3AW', 'Omeprazole_Cap E/C 20mg', 0.03558258199497268),
 ('CW5 5NX', 'Omeprazole_Cap E/C 20mg', 0.03453647138997736),
 ('CW7 1AT', 'Omeprazole_Cap E/C 20mg', 0.03666371289322109),
 ('DA1 2HA', 'Omeprazole_Cap E/C 20mg', 0.019244977658938185),
 ('DA11 8BZ', 'Amoxicillin_Cap 500mg', 0.019686834904226208),
 ('DN16 2AB', 'Amlodipine_Tab 5mg', 0.019925280199252802),
 ('DN22 7XF', 'Simvastatin_Tab 40mg', 0.019759286045686525),
 ('DN31 3AE', 'Omeprazole_Cap E/C 20mg', 0.03432952436761402),
 ('DN34 4GB', 'Omeprazole_Cap E/C 20mg', 0.03709507845509909),
 ('DN36 4QG', 'Omeprazole_Cap E/C 20mg', 0.04061400703549728),
 ('DN6 0HZ', 'Paracet_Tab 500mg', 0.025764099668243102),
 ('DN8 4BQ', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.021703061442945835),
 ('DY11 6SF', 'Omeprazole_Cap E/C 20mg', 0.021081859317153433),
 ('E15 4ES', 'Amlodipine_Tab 10mg', 0.02569068641412703),
 ('E7 0EP', 'Metformin HCl_Tab 500mg', 0.03372442576540291),
 ('FY2 0JG', 'Omeprazole_Cap E/C 20mg', 0.036313080627192455),
 ('FY4 1TJ', 'Omeprazole_Cap E/C 20mg', 0.042477967457644615),
 ('FY5 2TZ', 'Omeprazole_Cap E/C 20mg', 0.03540407051009112),
 ('FY5 3LF', 'Omeprazole_Cap E/C 20mg', 0.035122866094073016),
 ('FY7 8GU', 'Omeprazole_Cap E/C 20mg', 0.032058079778122195),
 ('FY8 5DZ', 'Omeprazole_Cap E/C 20mg', 0.02969960416717259),
 ('GL1 3PX', 'Omeprazole_Cap E/C 20mg', 0.025687801991914012),
 ('GL20 5GJ', 'Omeprazole_Cap E/C 20mg', 0.024283922848782818),
 ('GL20 5QQ', 'Omeprazole_Cap E/C 20mg', 0.02363625054425577),
 ('GL20 5RY', 'Omeprazole_Cap E/C 20mg', 0.02458872431356478),
 ('GL50 4DP', 'Omeprazole_Cap E/C 20mg', 0.024009042366605605),
 ('GU9 9QS', 'Omeprazole_Cap E/C 20mg', 0.027052485943893322),
 ('HA0 4UZ', 'Metformin HCl_Tab 500mg', 0.031142085766308784),
 ('HA3 7LT', 'Omeprazole_Cap E/C 20mg', 0.02504635488712953),
 ('HD6 1AT', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.021017471736896196),
 ('HG1 5AR', 'Omeprazole_Cap E/C 20mg', 0.02842489568845619),
 ('HR1 2JB', 'Omeprazole_Cap E/C 20mg', 0.028529603122966818),
 ('HR6 8HD', 'Omeprazole_Cap E/C 20mg', 0.027207967812149594),
 ('HU7 4DW', 'Salbutamol_Inha 100mcg (200 D) CFF', 0.02575475073921314),
 ('HU9 2LJ', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.0243192109011288)]

In [41]:
items_by_region = [("B11 4BW", "Salbutamol_Inha 100mcg (200 D) CFF", 0.0310589063)] * 100

In [18]:
items_by_region = [('B11 4BW', 'Salbutamol_Inha 100mcg (200 D) CFF', 0.031058906339360346), ('B12 9LP', 'Paracet_Tab 500mg', 0.02489310607391788), ('B18 7AL', 'Salbutamol_Inha 100mcg (200 D) CFF', 0.027111371172225472), ('B21 9RY', 'Metformin HCl_Tab 500mg', 0.03329358300834757), ('B23 6DJ', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.021384456106529576), ('B61 0AZ', 'Omeprazole_Cap E/C 20mg', 0.028713318284424378), ('B70 7AW', 'Paracet_Tab 500mg', 0.025135992162726547), ('B72 1RL', 'Omeprazole_Cap E/C 20mg', 0.020228765092141495), ('B8 1RZ', 'Metformin HCl_Tab 500mg', 0.021347750961484866), ('B9 5PU', 'Ventolin_Evohaler 100mcg (200 D)', 0.024826024522257815), ('B90 3LX', 'Omeprazole_Cap E/C 20mg', 0.026965103983080718), ('BA5 1XJ', 'Omeprazole_Cap E/C 20mg', 0.028261290947858113), ('BB11 2DL', 'Omeprazole_Cap E/C 20mg', 0.027381741821396993), ('BB2 1AX', 'Omeprazole_Cap E/C 20mg', 0.03428191046763188), ('BB3 1PY', 'Omeprazole_Cap E/C 20mg', 0.032683395995453356), ('BB4 5SL', 'Omeprazole_Cap E/C 20mg', 0.03747689029549087), ('BB4 7PL', 'Omeprazole_Cap E/C 20mg', 0.027477496877557173), ('BB7 2JG', 'Omeprazole_Cap E/C 20mg', 0.027980664806967485), ('BB8 0JZ', 'Atorvastatin_Tab 20mg', 0.021515746650768042), ('BB9 7SR', 'Omeprazole_Cap E/C 20mg', 0.02247662283190644), ('BD16 4RP', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.022780283004198414), ('BD19 5AP', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.02066220372715759), ('BD3 8QH', 'Atorvastatin_Tab 40mg', 0.031662850096882154), ('BD4 7SS', 'Atorvastatin_Tab 40mg', 0.03424183501960914), ('BH14 0DJ', 'Omeprazole_Cap E/C 20mg', 0.02838931332218254), ('BH18 8EE', 'Omeprazole_Cap E/C 20mg', 0.027092370049064923), ('BH23 3AF', 'Omeprazole_Cap E/C 20mg', 0.03546099290780142), ('BL1 3RG', 'Omeprazole_Cap E/C 20mg', 0.03362566656383588), ('BL1 8TU', 'Omeprazole_Cap E/C 20mg', 0.027729220222793487), ('BL2 6NT', 'Omeprazole_Cap E/C 20mg', 0.0271567320510379), ('BL3 5HP', 'Omeprazole_Cap E/C 20mg', 0.03129933420275929), ('BL9 0NJ', 'Omeprazole_Cap E/C 20mg', 0.032037565382786494), ('BL9 0SN', 'Omeprazole_Cap E/C 20mg', 0.03090454288711369), ('BN1 6AG', 'Lansoprazole_Cap 15mg (E/C Gran)', 0.021755523716160168), ('BN1 8DD', 'Aspirin Disper_Tab 75mg', 0.021517850460294887), ('BN9 9PW', 'Omeprazole_Cap E/C 20mg', 0.01855317763853853), ('BR2 9GT', 'Influenza_Vac Inact 0.5ml Pfs', 0.04301700334253742), ('BR3 3FD', 'Omeprazole_Cap E/C 20mg', 0.02865911645197545), ('BS16 3TD', 'Omeprazole_Cap E/C 20mg', 0.03752737892431249), ('BS23 3HQ', 'Omeprazole_Cap E/C 20mg', 0.030246216399367518), ('BS4 1WH', 'Omeprazole_Cap E/C 20mg', 0.029600778967867575), ('BS4 4HU', 'Omeprazole_Cap E/C 20mg', 0.037361354349095155), ('BS48 2XX', 'Omeprazole_Cap E/C 20mg', 0.030207346595095254), ('CA11 8HW', 'Omeprazole_Cap E/C 20mg', 0.027868623340321454), ('CB22 3HU', 'Omeprazole_Cap E/C 20mg', 0.038775726713346066), ('CB9 8HF', 'Omeprazole_Cap E/C 20mg', 0.03391110538046382), ('CH1 4DS', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.0257736189772634), ('CH41 8DB', 'Omeprazole_Cap E/C 20mg', 0.03327732469980738), ('CH44 5UF', 'Omeprazole_Cap E/C 20mg', 0.03327334826839032), ('CH62 5HS', 'Omeprazole_Cap E/C 20mg', 0.037778835690968446), ('CH62 6EE', 'Influenza_Vac Inact 0.5ml Pfs', 0.057585894269547), ('CH65 6TG', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.026067517902474142), ('CH66 3PB', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.03100619319552803), ('CM18 6LY', 'Omeprazole_Cap E/C 20mg', 0.026445315758738635), ('CR0 0JA', 'Salbutamol_Inha 100mcg (200 D) CFF', 0.021571724750715768), ('CT11 8AD', 'Omeprazole_Cap E/C 20mg', 0.022307039864291774), ('CV1 4FS', 'Omeprazole_Cap E/C 20mg', 0.028455180531743392), ('CV12 8NQ', 'Omeprazole_Cap E/C 20mg', 0.026444799282852902), ('CV21 2DN', 'Omeprazole_Cap E/C 20mg', 0.04102890311294875), ('CV6 2FL', 'Omeprazole_Cap E/C 20mg', 0.036250663502669624), ('CV6 6DR', 'Omeprazole_Cap E/C 20mg', 0.030544721504009817), ('CW1 3AW', 'Omeprazole_Cap E/C 20mg', 0.03558258199497268), ('CW5 5NX', 'Omeprazole_Cap E/C 20mg', 0.03453647138997736), ('CW7 1AT', 'Omeprazole_Cap E/C 20mg', 0.03666371289322109), ('DA1 2HA', 'Omeprazole_Cap E/C 20mg', 0.019244977658938185), ('DA11 8BZ', 'Amoxicillin_Cap 500mg', 0.019686834904226208), ('DN16 2AB', 'Amlodipine_Tab 5mg', 0.019925280199252802), ('DN22 7XF', 'Simvastatin_Tab 40mg', 0.018624361621210474), ('DN31 3AE', 'Omeprazole_Cap E/C 20mg', 0.03432952436761402), ('DN34 4GB', 'Omeprazole_Cap E/C 20mg', 0.03709507845509909), ('DN6 0HZ', 'Paracet_Tab 500mg', 0.025764099668243102), ('DN8 4BQ', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.021703061442945835), ('DY11 6SF', 'Omeprazole_Cap E/C 20mg', 0.021081859317153433), ('E15 4ES', 'Amlodipine_Tab 10mg', 0.02569068641412703), ('E7 0EP', 'Metformin HCl_Tab 500mg', 0.037244933982913224), ('FY2 0JG', 'Omeprazole_Cap E/C 20mg', 0.03627638093657511), ('FY4 1TJ', 'Omeprazole_Cap E/C 20mg', 0.04334478808705613), ('FY5 2TZ', 'Omeprazole_Cap E/C 20mg', 0.03540407051009112), ('FY5 3LF', 'Omeprazole_Cap E/C 20mg', 0.035122866094073016), ('FY7 8GU', 'Omeprazole_Cap E/C 20mg', 0.032058079778122195), ('FY8 5DZ', 'Omeprazole_Cap E/C 20mg', 0.02969960416717259), ('GL1 3PX', 'Omeprazole_Cap E/C 20mg', 0.025687801991914012), ('GL20 5GJ', 'Omeprazole_Cap E/C 20mg', 0.02412690753362688), ('GL50 4DP', 'Omeprazole_Cap E/C 20mg', 0.024009042366605605), ('GU9 9QS', 'Omeprazole_Cap E/C 20mg', 0.027052485943893322), ('HA0 4UZ', 'Metformin HCl_Tab 500mg', 0.027855843941147297), ('HA3 7LT', 'Omeprazole_Cap E/C 20mg', 0.02504635488712953), ('HD6 1AT', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.021017471736896196), ('HG1 5AR', 'Omeprazole_Cap E/C 20mg', 0.02842489568845619), ('HR1 2JB', 'Omeprazole_Cap E/C 20mg', 0.028529603122966818), ('HR6 8HD', 'Omeprazole_Cap E/C 20mg', 0.027207967812149594), ('HU7 4DW', 'Salbutamol_Inha 100mcg (200 D) CFF', 0.025607843137254904), ('HU9 2LJ', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.0243192109011288), ('IG7 4DF', 'Amlodipine_Tab 5mg', 0.01956475808155504), ('IP22 4WG', 'Omeprazole_Cap E/C 20mg', 0.02851095218241878), ('KT12 3LB', 'Omeprazole_Cap E/C 20mg', 0.01828471919895516), ('KT14 6DH', 'Amlodipine_Tab 5mg', 0.018667887710894296), ('KT16 8HZ', 'Amlodipine_Tab 5mg', 0.019319714781268066), ('KT6 6EZ', 'Omeprazole_Cap E/C 20mg', 0.02821316614420063), ('L31 0DJ', 'Omeprazole_Cap E/C 20mg', 0.029425653739448675)]

In [19]:
grader.score.dw__items_by_region(items_by_region)

==================
Your score:  1.0
==================

## Question 4: script_anomalies

Drug abuse is a source of human and monetary costs in health care. A first step in identifying practitioners that enable drug abuse is to look for practices where commonly abused drugs are prescribed unusually often. Let's try to find practices that prescribe an unusually high amount of opioids. The opioids （类鸦片） we'll look for are given in the list below.

These are generic names for drugs, not brand names. Generic drug names can be found using the `'bnf_code'` field in `scripts` along with the `chem` table.. Use the list of opioids provided above along with these fields to make a new field in the `scripts` data that flags whether the row corresponds with a opioid prescription.

In [10]:
# scripts = pd.read_csv('./dw-data/201701scripts_sample.csv.gz', compression='gzip')
# chem = pd.read_csv('./dw-data/chem.csv.gz', compression = 'gzip')

opioids = ['morphine', 'oxycodone', 'methadone', 'fentanyl', 'pethidine', 'buprenorphine', 'propoxyphene', 'codeine']
scripts.head(1)

  practice   bnf_code               bnf_name  items   nic  act_cost  quantity
0   N85639  0106020C0  Bisacodyl_Tab E/C 5mg      1  0.39      0.47        12

In [11]:
scripts = scripts.merge(chem, left_on  = 'bnf_code', right_on = 'CHEM SUB' , how = 'left')

In [12]:
scripts[scripts.NAME.isnull()]

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity,CHEM SUB,NAME
26,N85639,210102301,Able Spacer,1,4.39,4.08,1,NaN,NaN
30,N85647,210102301,Aerochamber Plus + Adult/Child/Infant Ma,1,8.11,7.52,1,NaN,NaN
1311,N81013,200202008,K-Lite 10cm x 4.5m M/Layer Compress Band,1,5.05,4.69,5,NaN,NaN
1312,N81013,200301000,Atrauman 5cm x 5cm Ktd Polyester Dress,2,2.70,2.50,10,NaN,NaN
1313,N81013,200301000,Atrauman 20cm x 30cm Ktd Polyester Dress,3,24.36,22.57,14,NaN,NaN
1314,N81013,200301000,Melolin 5cm x 5cm Pfa Plas Faced Dress,1,3.40,3.16,20,NaN,NaN
1315,N81013,200301000,Mepore 7cm x 8cm Pfa + Adh Border Dress,1,1.10,1.03,10,NaN,NaN
1316,N81013,200301000,Mepore 10cm x 11cm Pfa + Adh Border Dres,1,2.20,2.05,10,NaN,NaN
1317,N81013,200301001,Inadine 5cm x 5cm Povidone Iodine Fabric,3,19.80,18.37,60,NaN,NaN
1318,N81013,200301001,Inadine 9.5cm x 9.5 cm Povidone Iodine F,1,4.90,4.55,10,NaN,NaN
1319,N81013,200301001,Dressit Ster Dress Pack,4,19.80,18.34,33,NaN,NaN
1320,N81013,200301001,Tegaderm Film 6cm x 7cm VP Adh Film Dres,1,3.12,2.89,8,NaN,NaN
1321,N81013,200301002,C-View 6cm x 7cm VP Adh Film Dress,1,1.90,1.77,5,NaN,NaN
1322,N81013,200301003,Zetuvit E 20cm x 40cm Pfa Cellulose Dres,1,22.20,20.55,20,NaN,NaN
1323,N81013,200301004,Zetuvit E (Non-Ster) 10cm x 20cm Pfa Cel,1,1.26,1.18,14,NaN,NaN
1324,N81013,200301004,Zetuvit E (Non-Ster) 20cm x 40cm Pfa Cel,2,2.24,2.10,8,NaN,NaN
1325,N81013,200301005,Hydrofilm 10cm x 25cm Vp Adh Film Dress,4,6.56,6.12,8,NaN,NaN
1326,N81013,200306000,Allevyn Adh 10cm x 10cm Wound Dress Poly,1,44.20,40.93,20,NaN,NaN
1327,N81013,200306000,Allevyn 10cm x 10cm Wound Dress Polyuret,1,25.20,23.34,10,NaN,NaN
1328,N81013,200309000,Mepitel 8cm x 10cm Wound Dress Soft Slc,1,14.00,12.97,5,NaN,NaN
1329,N81013,200309000,Mepilex Border Lite 4cm x 5cm Wound Dres,1,18.40,17.05,20,NaN,NaN
1330,N81013,200309000,Mepilex Border 7cm x 7.5cm Wound Dress S,2,67.50,62.52,50,NaN,NaN
1331,N81013,200309000,Allevyn Gentle Border 7.5cm x 7.5cm Woun,2,45.30,41.95,30,NaN,NaN
1332,N81013,200309000,Allevyn Gentle Border 10cm x 10cm Wound,1,22.10,20.47,10,NaN,NaN
1333,N81013,200316000,Allevyn Gentle 15cm x 15cm Wound Dress S,1,42.50,39.36,10,NaN,NaN
1334,N81013,200317001,Durafiber 10cm x 10cm Wound Dress Protea,2,87.60,81.10,40,NaN,NaN
1335,N81013,200317001,Durafiber Ag 5cm x 5cm Wound Dress Prote,1,35.80,33.15,20,NaN,NaN
1336,N81013,200319000,Acticoat 5cm x 5cm Wound Dress Silver Ct,1,35.40,32.78,10,NaN,NaN
1337,N81013,200502002,Laryngofoam Beige 5.1cm x 6.2cm Tracheo,1,26.04,24.11,60,NaN,NaN
1338,N81013,200502002,Laryngofoam Beige 6.3cm x 6.5cm Tracheo,1,13.02,12.05,30,NaN,NaN
...,...,...,...,...,...,...,...,...,...
973980,H81615,231534515,Pelican_Release Non-Sting Adh Remover A/,2,38.44,35.62,4,NaN,NaN
973981,H81615,231560015,C D Medical_Peel Easy Adh Remover Spy 50,1,28.40,26.29,4,NaN,NaN
973982,H81615,232502625,AMI_Suportx Ostomy Support Mens Shorts D,1,19.62,18.16,2,NaN,NaN
973983,H81615,232502625,AMI_Suportx Ostomy Support Mens Trunks D,1,39.24,36.33,4,NaN,NaN
973984,H81615,233510037,Coloplast_SenSura Midi Closed Bag S/Cove,1,177.50,164.32,60,NaN,NaN
973985,H81615,234506045,Bullen_NA'Scent Odour Eliminator,1,11.97,11.08,236,NaN,NaN
973986,H81615,234510045,Coloplast_Brava Lubricating Deod 240ml,1,8.46,7.84,1,NaN,NaN
973987,H81615,234533745,Respond_OstoMart OstoZyme M/Odour Neutra,1,16.16,14.96,2,NaN,NaN
973988,H81615,234544045,Shaw_Forest Breeze Deod,1,7.70,7.14,2,NaN,NaN
973989,H81615,236007062,Dansac_Nova 1 Drnbl + E/Fld Ileo Bag Sym,1,176.16,163.09,60,NaN,NaN
973990,H81615,236007063,Dansac_Nova 1 Convex E/Fld Drnbl Ileo Ba,1,245.28,227.07,60,NaN,NaN
973991,H81615,236010063,Coloplast_Sensura Mio Maxi DrnblBag Grey,1,99.63,92.23,30,NaN,NaN
973992,H81615,236056062,Welland_FreeStyle Vie Convex Drnbl Pch M,1,220.75,204.36,50,NaN,NaN
973993,H81615,238009080,CliniMed_LBF Ster No Sting Barrier Film,2,76.14,70.50,3,NaN,NaN
973994,H81615,238020980,H & R_Proshield Plus Skin Prote 115g,9,119.28,110.51,12,NaN,NaN
973995,H81615,238031080,3m Health Care_Cavilon No Sting Barrier,4,141.00,130.54,180,NaN,NaN
973996,H81615,238031080,3m Health Care_Cavilon Durable Barrier C,2,16.24,15.05,2,NaN,NaN
973997,H81615,238033680,Opus_SkinSafe Non Sting Prote Film,1,36.76,34.04,1,NaN,NaN
973998,H81615,238048080,Convatec_Orabase Paste 30g,3,8.56,7.93,4,NaN,NaN
973999,H81615,238501085,Hollister_Adapt Barrier Rings 98mm,2,180.08,166.74,80,NaN,NaN
974000,H81615,238510085,Coloplast_Brava Mouldable Rings 48mm x 2,1,58.39,54.05,30,NaN,NaN
974001,H81615,239401097,Hollister_Conform 2 Flat Barrier +Adh 45,1,98.28,90.98,30,NaN,NaN
974002,H81615,239407096,Dansac_Nova 2 Flng 43mm P/Cut 30mm,1,47.46,43.94,15,NaN,NaN
974003,H81615,239407098,Dansac_NovaLife 2 Open Pouch Maxi Opqe 4,1,212.04,196.30,120,NaN,NaN
974004,H81615,239410093,Coloplast_SenSura Flex Drnbl Bag Maxi Op,2,105.02,97.22,60,NaN,NaN
974005,H81615,239410100,Coloplast_SenSura Mio Flex B/Plt 50mm C/,1,78.92,73.06,20,NaN,NaN
974006,H81615,239410100,Coloplast_SenSura Mio Flex Clsd Bag Mini,1,106.36,98.46,60,NaN,NaN
974007,H81615,239410100,Coloplast_SenSura Mio Flex Clsd Bag Midi,1,159.54,147.69,90,NaN,NaN
974008,H81615,239607096,Dansac_Nova 1 Convex Urost Pouch Clr C/F,2,329.76,305.28,60,NaN,NaN
974009,H81615,239610096,Coloplast_SenSura Mio Urost Bag Maxi Tra,1,182.48,168.93,30,NaN,NaN

In [13]:
opioids_str = '|'.join(opioids)
print(opioids_str)

morphine|oxycodone|methadone|fentanyl|pethidine|buprenorphine|propoxyphene|codeine

In [14]:
scripts['opioids_flag'] =  (scripts['NAME'].str.contains(opioids_str, case=False) | scripts['bnf_name'].str.contains(opioids_str, case=False))
# scripts['opioids_flag'] =  scripts['opioids_flag'].fillna(0).astype('int')

In [15]:
scripts[scripts.opioids_flag == 0].head(2)

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity,CHEM SUB,NAME,opioids_flag
0,N85639,0106020C0,Bisacodyl_Tab E/C 5mg,1,0.39,0.47,12,0106020C0,Bisacodyl,False
1,N85639,0106040M0,Movicol Plain_Paed Pdr Sach 6.9g,1,4.38,4.07,30,0106040M0,Macrogol 3350,False

In [16]:
# scripts_per_practice[scripts_per_practice['opioids_practice'] == 1].head()

Now for each practice calculate the proportion of its prescriptions containing opioids.

**Hint:** Consider the following list: `[0, 1, 1, 0, 0, 0]`. What proportion of the entries are 1s? What is the mean value?

In [17]:
scripts_per_practice = scripts.groupby('practice').agg({'opioids_flag':'mean'})

In [18]:
scripts.shape

(974010, 10)

In [18]:
scripts_ori = scripts.copy()
scripts_ori_bnf_c = scripts_ori.groupby('practice')['bnf_code']\
.count().reset_index().merge(practices, 
                             left_on = 'practice', right_on ='code', how = 'left').reset_index()\
.rename(columns={'bnf_code':'bnf_sum'})[['practice','bnf_sum']]
#  ('NORTHGATE VILLAGE SURGERY', 1.6838489125165406, 1304)]

In [19]:
# opioids_per_practice = np.mean(scripts_per_practice['opioids_practice'])

overall_opioids_rate = np.mean(scripts.opioids_flag)
overall_opioids_std =  scripts.opioids_flag.std()

In [20]:
# opioids_per_practice,
overall_opioids_rate, overall_opioids_std

(0.03578300017453619, 0.1857487886805953)

How do these proportions compare to the overall opioid prescription rate? Subtract off the proportion of all prescriptions that are opioids from each practice's proportion.

In [21]:
relative_opioids_per_practice = scripts_per_practice['opioids_flag'] - overall_opioids_rate

In [22]:
relative_opioids_per_practice

practice
A81005   -0.002648
A81007    0.007486
A81011    0.010743
A81012    0.006978
A81017    0.002339
            ...
Y05570    0.055126
Y05583   -0.035783
Y05597   -0.035783
Y05660   -0.012728
Y05670   -0.035783
Name: opioids_flag, Length: 856, dtype: float64

Now that we know the difference between each practice's opioid prescription rate and the overall rate, we can identify which practices prescribe opioids at above average or below average rates. However, are the differences from the overall rate important or just random deviations? In other words, are the differences from the overall rate big or small?

To answer this question we have to quantify the difference we would typically expect between a given practice's opioid prescription rate and the overall rate. This quantity is called the **standard error**, and is related to the **standard deviation**, $\sigma$. The standard error in this case is

$$ \frac{\sigma}{\sqrt{n}} $$

where $n$ is the number of prescriptions each practice made. Calculate the standard error for each practice. Then divide `relative_opioids_per_practice` by the standard errors. We'll call the final result `opioid_scores`.

In [42]:
scripts_ori.groupby('practice').agg({'bnf_code':'count'})

          bnf_code
practice
A81005        1509
A81007        1456
A81011        1569
A81012        1333
A81017        2151
...            ...
Y05570          22
Y05583          28
Y05597          18
Y05660         347
Y05670          12

[856 rows x 1 columns]

In [44]:
standard_error_per_practice = scripts.opioids_flag.std() / (scripts_ori.groupby('practice').agg({'bnf_code':'count'}).bnf_code)**0.5
# standard_error_per_practice = scripts_per_practice.opioids_flag.std() / (scripts_per_practice.bnf_sum)**0.5
opioid_scores = (relative_opioids_per_practice / standard_error_per_practice)

In [45]:
relative_opioids_per_practice ,standard_error_per_practice

(practice
 A81005   -0.002648
 A81007    0.007486
 A81011    0.010743
 A81012    0.006978
 A81017    0.002339
             ...
 Y05570    0.055126
 Y05583   -0.035783
 Y05597   -0.035783
 Y05660   -0.012728
 Y05670   -0.035783
 Name: opioids_flag, Length: 856, dtype: float64, practice
 A81005    0.004782
 A81007    0.004868
 A81011    0.004689
 A81012    0.005088
 A81017    0.004005
             ...
 Y05570    0.039602
 Y05583    0.035103
 Y05597    0.043781
 Y05660    0.009972
 Y05670    0.053621
 Name: bnf_code, Length: 856, dtype: float64)

In [46]:
opioid_scores

practice
A81005   -0.553878
A81007    1.537864
A81011    2.291022
A81012    1.371516
A81017    0.583967
            ...
Y05570    1.392011
Y05583   -1.019365
Y05597   -0.817310
Y05660   -1.276460
Y05670   -0.667331
Length: 856, dtype: float64

In [31]:
practices.sort_values(['code','name']).groupby('code').head(1).reset_index()

,index,code,name,addr_1,addr_2,borough,village,post_code
0,0,A81001,THE DENSHAM SURGERY,THE HEALTH CENTRE,LAWSON STREET,STOCKTON ON TEES,CLEVELAND,TS18 1HU
1,1,A81002,QUEENS PARK MEDICAL CENTRE,QUEENS PARK MEDICAL CTR,FARRER STREET,STOCKTON ON TEES,CLEVELAND,TS18 2AW
2,2,A81003,VICTORIA MEDICAL PRACTICE,THE HEALTH CENTRE,VICTORIA ROAD,HARTLEPOOL,CLEVELAND,TS26 8DB
3,11915,A81004,BLUEBELL MEDICAL CENTRE,TRIMDON AVENUE,ACKLAM,MIDDLESBROUGH,NaN,TS5 8SB
4,4,A81005,SPRINGWOOD SURGERY,SPRINGWOOD SURGERY,RECTORY LANE,GUISBOROUGH,NaN,TS14 7DJ
5,5,A81006,TENNANT STREET MEDICAL PRACTICE,TENNANT ST MED PRACT,FARRER STREET,STOCKTON ON TEES,CLEVELAND,TS18 2AT
6,6,A81007,BANKHOUSE SURGERY,ONE LIFE HARTLEPOOL,PARK ROAD,HARTLEPOOL,CLEVELAND,TS24 7PW
7,7,A81008,ALBERT HOUSE CLINIC,LOW GRANGE HEALTH VILLAGE,NORMANBY ROAD,MIDDLESBROUGH,CLEVELAND,TS6 6TD
8,8,A81009,VILLAGE MEDICAL CENTRE,THE VILLAGE MEDICAL CTR,400/404 LINTHORPE ROAD,MIDDLESBROUGH,CLEVELAND,TS5 6HF
9,9,A81011,CHADWICK PRACTICE,ONE LIFE HARTLEPOOL,PARK ROAD,HARTLEPOOL,CLEVELAND,TS24 7PW
10,10,A81012,WESTBOURNE MEDICAL CENTRE,WESTBOURNE MEDICAL CENTRE,7 TRINITY MEWS N. ORMESBY,MIDDLESBROUGH,NaN,TS3 6AL
11,11,A81013,BROTTON SURGERY,BROTTON SURGERY,ALFORD ROAD BROTTON,SALTBURN BY SEA,NaN,TS12 2FF
12,12,A81014,QUEENSTREE PRACTICE,THE HEALTH CENTRE,QUEENSWAY,BILLINGHAM,CLEVELAND,TS23 2LA
13,13,A81015,LAGAN SURGERY,LAGAN SURGERY,20 KIRKLEATHAM STREET,REDCAR,CLEVELAND,TS10 1TZ
14,14,A81016,PARK SURGERY,PARK SURGERY ONE LIFE,LINTHORPE ROAD,MIDDLESBROUGH,CLEVELAND,TS1 3QY
15,15,A81017,WOODBRIDGE PRACTICE,THE HEALTH CENTRE,TRENCHARD AVE THORNABY,STOCKTON ON TEES,CLEVELAND,TS17 0EE
16,16,A81018,BENTLEY MEDICAL PRACTICE,REDCAR PRIMARY CARE HOSP,WEST DYKE ROAD,REDCAR,CLEVELAND,TS10 4NW
17,17,A81019,CROSSFELL HEALTH CENTRE,CROSSFELL ROAD,BERWICK HILLS,MIDDLESBROUGH,CLEVELAND,TS3 7RL
18,18,A81020,MARTONSIDE MEDICAL CENTRE,MARTONSIDE MEDICAL CENTRE,1A MARTONSIDE WAY,MIDDLESBROUGH,CLEVELAND,TS4 3BU
19,19,A81021,NORMANBY MEDICAL CENTRE,NORMANBY MEDICAL CENTRE,LOW GRANGE HV NORMANBY RD,MIDDLESBROUGH,CLEVELAND,TS6 6TD
20,20,A81022,HILLSIDE PRACTICE,HILLSIDE PRACTICE,WINDERMERE DRIVE SKELTON,SALTBURN BY THE SEA,CLEVELAND,TS12 2TG
21,21,A81023,THE ENDEAVOUR PRACTICE,THE HEALTH CENTRE,20 CLEVELAND SQUARE,MIDDLESBROUGH,CLEVELAND,TS1 2NX
22,22,A81025,THE DOVECOT SURGERY,THE HEALTH CENTRE,LAWSON STREET,STOCKTON ON TEES,CLEVELAND,TS18 1HU
23,23,A81026,THE LINTHORPE SURGERY,378 LINTHORPE ROAD,NaN,MIDDLESBROUGH,CLEVELAND,TS5 6HA
24,24,A81027,YARM MEDICAL PRACTICE,YARM MEDICAL PRACTICE,MULBERRY HOUSE,1 WORSALL ROAD,YARM CLEVELAND,TS15 9DD
25,25,A81029,PROSPECT SURGERY,THE HEALTH CENTRE,PO BOX 101E,20 CLEVELAND SQUARE,MIDDLESBROUGH,TS1 2NX
26,26,A81030,BOROUGH ROAD & NUNTHORPE MEDICAL GROUP,167A BOROUGH ROAD,NaN,MIDDLESBROUGH,NaN,TS1 3RY
27,27,A81031,HAVELOCK GRANGE PRACTICE,ONE LIFE HARTLEPOOL,PARK ROAD,HARTLEPOOL,CLEVELAND,TS24 7PW
28,28,A81032,THE GARTH,THE GARTH SURGERY,RECTORY LANE,GUISBOROUGH,CLEVELAND,TS14 7DJ
29,29,A81033,OAKFIELD MEDICAL PRACTICE,OAKFIELDS MED PRACTICE,1 TRINITY MEWS N. ORMESBY,MIDDLESBROUGH,NaN,TS3 6AL
...,...,...,...,...,...,...,...,...
10813,11895,Y05719,CROYDON GP HUBS,PURLEY GP HUB,MEM HOSP 856 BRIGHTON RD,PURLEY,NaN,CR8 2YL
10814,11896,Y05720,CHS URGENT CARE CENTRE,PHARMACY DEPARTMENT,530 LONDON ROAD,CROYDON,SURREY,CR7 7YE
10815,11897,Y05721,SEFTON 0-19 SERVICE,HOLLINS PARK HOSPITAL,HOLLINS LANE,WARRINGTON,CHESHIRE,WA2 8WA
10816,11898,Y05724,LYMPHOEDEMA SERVICE FOR SANDWELL CCG,BLOCK B,WEST HEATH HOSPITAL,BIRMINGHAM,WEST MIDLANDS,B38 8HR
10817,12011,Y05725,ACUTE CARE AT HOME CENTRAL,TRURO HEALTH PARK,INFIRMARY HILL,TRURO,CORNWALL,TR1 2JA
10818,11899,Y05727,ADDACTION HARTLEPOOL,HART TREATMENT CENTRE,WHITBY STREET,HARTLEPOOL,NaN,TS24 7AB
10819,11900,Y05730,SWAN ACCESS HUB,CHANDLER HOUSE,POOLSTOCK LANE,WIGAN,NaN,WN3 5HL
10820,11787,Y05732,BROMLEY COMMUNITY HEADACHE SERVICE,BROMLEY PARK SURGERY,DALY DRIVE,BROMLEY,NaN,BR1 2FF
10821,11901,Y05733,PARKFIELDS SURGERY,1217 LONDON ROAD,ALVASTON,DERBY,DERBYSHIRE,DE24 8QJ
10822,11902,Y05735,SEDGEFIELD PRIMARY CARE SERVICES,JUBILEE M/G COBBLERS HALL,CARERS WAY BURN LANE,NEWTON AYCLIFFE,COUNTY DURHAM,DL5 4SE
10823,11903,Y05736,BISHOP AUCKLAND PRIMARY CARE SERVICES,STATION VIEW MEDICAL CTR,29A ESCOMB RD,BISHOP AUCKLAND,COUNTY DURHAM,DL14 6AB
10824,11904,Y05737,BDCT 0-19 CHILDRENS PH SERVICE,BRADFORD DISTRICT CT,NEW MILL,VICTORIA ROAD SALTAIRE,NaN,BD18 3LD
10825,11905,Y05738,PETERLEE PRIMARY CARE SERVICES,PETERLEE HEALTH CENTRE,BEDE WAY,PETERLEE,COUNTY DURHAM,SR8 1AD
10826,11906,Y05740,LIFELINE YOUNG PEOPLES SERVICE,11 WARDS END,NaN,HALIFAX,WEST YORKSHIRE,HX1 1BX
10827,11907,Y05741,LEW GP EXTENDED ACCESS SERVICE,GP EAS AMBULATORY CENTRE,LEWISHAM HOSPITAL,HIGH STREET LEWISHAM,LONDON,SE13 6LH
10828,11908,Y05742,NORTH EAST LINCOLNSHIRE DERMATOLOGY,CROMWELL PCC,CROMWELL ROAD,GRIMSBY,NORTH EAST LINCOLNSHIRE,DN31 2BH
10829,12012,Y05743,NEWARK ACUTE HOME VISITING SERVICE,PICS,UNIT H4 ASH TREE COURT,NOTTINGHAM,NaN,NG8 6PY
10830,12013,Y05744,NEWMEDICA COMMUNITY OPHTHALMOLOGY,CROMWELL PCC,CROMWELL ROAD,GRIMSBY,NORTH EAST LINCOLNSHIRE,DN31 2BH
10831,12014,Y05748,EAST KENT DRUG AND ALCOHOL SERVICE,TRANSPORT HOUSE,DRUM LANE,ASHFORD,KENT,TN23 1LQ
10832,11909,Y05749,GP ACCESS SERVICE,WIRRAL CCG OLD MARKET HSE,HAMILTON STREET,BIRKENHEAD,NaN,CH41 5AL
10833,12015,Y05752,MALVERN FRAILTY UNIT,MALVERN COMM. HOSPITAL,185 WORCESTER ROAD,MALVERN,WORCESTERSHIRE,WR14 1EX
10834,11910,Y05753,EXTENDED HOURS SERVICE-ONE LIFE,ONE LIFE HARTLEPOOL,PARK ROAD,HARTLEPOOL,CLEVELAND,TS24 7PW
10835,11911,Y05754,EXTENDED HOURS SERVICE-TENNANT STREET,TENNANT ST MEDICAL CENTRE,TENNANT STREET,STOCKTON-ON-TEES,CLEVELAND,TS18 2AT
10836,11912,Y05755,EXTENDED HOURS SERVICE-WOODBRIDGE,THE HEALTH CENTRE,TRENCHARD AVE THORNABY,STOCKTON-ON-TEES,CLEVELAND,TS17 0EE
10837,12016,Y05757,VC WEST LANCS HC-UCC,ORMSKIRK DG HOSPITAL,WIGAN ROAD,ORMSKIRK,LANCASHIRE,L39 2AZ
10838,12017,Y05758,VC SKELMERSDALE UCC,CONCOURSE SHOPPING CENTRE,116-8 SOUTH WAY,SKELMERSDALE,LANCASHIRE,WN8 6LJ
10839,12018,Y05762,WEST MERTON ACCESS HUB,THE NELSON HEALTH CENTRE,KINGSTON ROAD,WIMBLEDON,NaN,SW20 8DA
10840,12019,Y05763,ELY LOCAL URGENT CARE SERVICE,PRINCESS OF WALES HOSP,LYNN ROAD,ELY,CAMBRIDGSHIRE,CB6 1DN
10841,11913,Y05764,MINOR INJURIES UNIT,JOHNSON COMMUNITY HOSP,SPALDING ROAD PINCHBECK,SPALDING,LINCOLNSHIRE,PE11 3PB
10842,11914,Y05771,URGENT CARE CENTRE NORTHWICK PARK HOSP,NORTHWICK PARK HOSPITAL,WATFORD ROAD,HARROW,NaN,HA1 3UJ

In [32]:
scripts_ori_bnf_c.columns

Index(['practice', 'bnf_sum'], dtype='object')

In [48]:
df = pd.DataFrame(opioid_scores, columns = ['z_score'])
# df['bnf_sum'] = scripts_per_practice.bnf_sum
df = df.reset_index().merge(scripts_ori_bnf_c.reset_index(), left_on = 'practice', right_on = 'practice')
df = df.reset_index().sort_values('z_score',ascending= False )
practices = practices.sort_values(['code','name']).groupby('code').head(1)
df = df.merge(practices, left_on = 'practice', right_on = 'code', how = 'left')[['code','name','z_score','bnf_sum']]
print (df.shape)

(985, 4)

In [30]:
df.head()

     code                             name    z_score  bnf_sum
0  Y01852        NATIONAL ENHANCED SERVICE  11.699209        7
1  Y03006         OUTREACH SERVICE NH / RH   7.341145        2
2  Y03668  BRISDOC HEALTHCARE SERVICES OOH   6.153041       60
3  G81703           H&R P C SPECIAL SCHEME   5.125033       36
4  Y04997                   HMR BARDOC OOH   4.962091      321

The quantity we have calculated in `opioid_scores` is called a **z-score**:

$$ \frac{\bar{X} - \mu}{\sqrt{\sigma^2/n}} $$

Here $\bar{X}$ corresponds with the proportion for each practice, $\mu$ corresponds with the proportion across all practices, $\sigma^2$ corresponds with the variance of the proportion across all practices, and $n$ is the number of prescriptions made by each practice. Notice $\bar{X}$ and $n$ will be different for each practice, while $\mu$ and $\sigma$ are determined across all prescriptions, and so are the same for every z-score. The z-score is a useful statistical tool used for hypothesis testing, finding outliers, and comparing data about different types of objects or events.

Now that we've calculated this statistic, take the 100 practices with the largest z-score. Return your result as a list of tuples in the form `(practice_name, z-score, number_of_scripts)`. Sort your tuples by z-score in descending order. Note that some practice codes will correspond with multiple names. In this case, use the first match when sorting names alphabetically.

In [49]:
anomalies = []
for i in range(100):
    ans_tuple = (df['name'][i],df['z_score'][i] , df['bnf_sum'][i])
    anomalies.append(ans_tuple)

In [50]:
anomalies

[('NATIONAL ENHANCED SERVICE', 11.699209097759136, 7),
 ('OUTREACH SERVICE NH / RH', 7.341144822045991, 2),
 ('BRISDOC HEALTHCARE SERVICES OOH', 6.1530412888348085, 60),
 ('H&R P C SPECIAL SCHEME', 5.125032967275007, 36),
 ('HMR BARDOC OOH', 4.962091311252586, 321),
 ('DARWEN HEALTHCARE', 4.956679429873604, 1919),
 ('INTEGRATED CARE 24 LTD (CWSX OOH)', 4.892374195851049, 426),
 ('THE LIMES MEDICAL PRACTICE', 4.537883674165237, 1323),
 ('IC24 LTD (BRIGHTON & HOVE OOH)', 4.3382100812948154, 357),
 ('OLDHAM 7 DAY ACCESS HUB2 OOH', 4.313726724643943, 56),
 ('IC24 LTD (NORFOLK & WISBECH OOH)', 4.260985551001909, 489),
 ('ROSSENDALE MIU & OOH', 4.258410699487984, 18),
 ('BURY WALK-IN CENTRE', 4.152942664215405, 138),
 ('IC24 LTD (HORSHAM & MID SUSSEX OOH)', 3.7841863697802585, 215),
 ('LCW HOUNSLOW CCG OOH', 3.5846850269075774, 69),
 ('WEEKEND WORKING EASINGTON NORTH', 3.5686610126605642, 278),
 ('COMPASS ENFIELD', 3.559947987224374, 7),
 ('BASSETLAW DRUG & ALCOHOL SERVICE', 3.534354014906708, 2),
 ('THE PARK SURGERY', 3.515360526768244, 969),
 ('CHAPEL STREET SURGERY', 3.489673293452054, 1505),
 ('BEECHWOOD MEDICAL PRACTICE', 3.473902107326664, 1553),
 ('BASSETLAW HOSPICE OF THE GOOD SHEPHERD', 3.456063571231854, 46),
 ('CARDEN SURGERY', 3.455174292983251, 1375),
 ('GP IN A&E (WIC)', 3.3978131408148813, 87),
 ('NORTHAMPTONSHIRE OOH SERVICE', 3.3965412266669794, 382),
 ('NORTHAMPTONSHIRE OOH SERVICE', 3.3965412266669794, 382),
 ('WORDEN MEDICAL CENTRE', 3.3415503735963052, 1899),
 ('BRISDOC HEALTHCARE SERVICES OOH', 3.337061645021116, 566),
 ('BURY OOH', 3.324230940753404, 292),
 ('IC24 SOUTHEND/CP&R CCG OOH', 3.2239221883539257, 336),
 ('IC24 SOUTHEND/CP&R CCG OOH', 3.2239221883539257, 336),
 ('IC24 LTD (CRAWLEY OOH)', 3.196512931845654, 173),
 ('EASTBOURNE  HAILSHAM & SEAFORD OOH', 2.9921865871245084, 255),
 ('THE ROSEBERRY PRACTICE', 2.9791170145982804, 1451),
 ('SHAFTESBURY MEDICAL CTR.', 2.9005514357514013, 2128),
 ('THE RICHMOND HILL PRACTICE', 2.8544578512934633, 1731),
 ('THE RICHMOND HILL PRACTICE', 2.8544578512934633, 1731),
 ('DGS OOH (INTEGRATED CARE 24 LTD)', 2.7983127436197703, 325),
 ('THE LAKESIDE PRACTICE', 2.7850580931805404, 1554),
 ('DEWSBURY MSK SERVICE', 2.7745661142711002, 3),
 ('BRISDOC HEALTHCARE SERVICES OOH', 2.723659563372342, 74),
 ('HALLIWELL SURGERY 1', 2.6806379739915567, 1126),
 ('THE ROYTON & CROMPTON FAMILY PRACTICE', 2.663144087298262, 2056),
 ('PRACTICE 3  MEDICAL CENTRE  BRIDLINGTON', 2.65298799773282, 1937),
 ('LCWUCC - IUC NCL', 2.595722179935655, 443),
 ('THE CREST FAMILY PRACTICE', 2.4988492604750943, 1294),
 ('DR MOKASHI', 2.4890714060675103, 1343),
 ('PERKINS PRACTICE', 2.4756195255085736, 900),
 ('DARLASTON HEALTH CENTRE', 2.4496428330996367, 996),
 ("DR MA SIMS' PRACTICE", 2.4322597343150587, 1859),
 ('1/LOWER BROUGHTON MEDICAL PRACTICE', 2.425476011429166, 1046),
 ('CORNWALLIS PLAZA SURGERY', 2.420949472710108, 2328),
 ('FAIRMORE MEDICAL PRACTICE', 2.3742825815628827, 1290),
 ('LAWLEY MEDICAL PRACTICE', 2.366260143172823, 1411),
 ('LAWLEY MEDICAL PRACTICE', 2.366260143172823, 1411),
 ("PEEL GP'S", 2.347147531096015, 1559),
 ("PEEL GP'S", 2.347147531096015, 1559),
 ("PEEL GP'S", 2.347147531096015, 1559),
 ('EASTLANDS MEDICAL CENTRE', 2.323896798673042, 1370),
 ('MAGHULL HEALTH CENTRE (DR SAPRE)', 2.3177181896392915, 1323),
 ('INTEGRATED CARE 24 LIMITED OOH', 2.313669433658373, 511),
 ('IC24 LTD (HWLH OOH)', 2.297074430930294, 216),
 ('CHADWICK PRACTICE', 2.2910218972295384, 1569),
 ('WILLOW BANK SURGERY', 2.2860180888356245, 1937),
 ('C&WPT OOH SERVICE', 2.273421069837655, 341),
 ('THE MERRYWOOD PRACTICE', 2.262092186741878, 1236),
 ('LEYLAND SURGERY', 2.2560788720197227, 1213),
 ('LEYLAND SURGERY', 2.2560788720197227, 1213),
 ('WALKDEN MEDICAL PRACTICE', 2.246395094348847, 1577),
 ('RADCLIFFE MEDICAL PRACTICE', 2.2387866552501974, 1554),
 ('RIBBLESDALE GP-DR SUBBIAH', 2.2002464085284927, 1102),
 ('RIBBLESDALE GP-DR SUBBIAH', 2.2002464085284927, 1102),
 ('THE MAZHARI & KHAN PRACTICE', 2.196878071219362, 913),
 ('JAMES ALEXANDER FAMILY PRACTICE', 2.190716172677506, 1636),
 ('JAMES ALEXANDER FAMILY PRACTICE', 2.190716172677506, 1636),
 ('JAMES ALEXANDER FAMILY PRACTICE', 2.190716172677506, 1636),
 ('B&H INTERMEDIATE CARE SERVICE', 2.1890666499277667, 456),
 ('HARDEN SURGERY', 2.153423696275174, 1229),
 ('THE GATEWAY MEDICAL PRACTICE', 2.1528616384833215, 1350),
 ('QUAYSIDE MEDICAL PRACTICE', 2.1522646554859275, 1423),
 ('FISHPONDS FAMILY PRACTICE', 2.0792092877784474, 1632),
 ('HASTINGS AND ROTHER OOH', 2.078858201573084, 291),
 ('DRS CLOAK  CHOI AND MILLIGAN', 2.0453130141748668, 1663),
 ("ST MARY'S SURGERY", 2.044901866222211, 981),
 ('THE THORNTON PRACTICE', 1.9925749661350594, 1972),
 ('IC24 LTD (EAST SURREY OOH)', 1.9550613103176373, 194),
 ('CORNISHWAY GROUP PRACTICE', 1.9519395564457478, 1507),
 ('CORNISHWAY GROUP PRACTICE', 1.9519395564457478, 1507),
 ('CORNISHWAY GROUP PRACTICE', 1.9519395564457478, 1507),
 ('PREMIER HEALTH TEAM', 1.937931370947089, 876),
 ('CONCORD MEDICAL PRACTICE', 1.9266974922589564, 1388),
 ('COULBY MEDICAL PRACTICE', 1.9206680770163531, 1587),
 ('PARKSIDE MEDICAL CENTRE', 1.9158341104582104, 1316),
 ('THE DISCOVERY PRACTICE', 1.9029013772868153, 1269),
 ('ANCORA MEDICAL PRACTICE', 1.8823173708680383, 2349),
 ('DARWEN HEALTHLINK', 1.878052453774041, 2021),
 ('ROOLEY LANE MED. CENTRE', 1.862678689699458, 1523),
 ('JALAL PRACTICE', 1.8547262948191738, 887),
 ('GREAT HOMER STREET MEDICAL CENTRE', 1.8034316198429485, 1064),
 ('THE CRESCENT SURGERY', 1.7986809233799992, 1735)]

In [38]:
anomalies

[('NATIONAL ENHANCED SERVICE', 11.699209097759136, 7),
 ('OUTREACH SERVICE NH / RH', 7.341144822045991, 2),
 ('BRISDOC HEALTHCARE SERVICES OOH', 6.1530412888348085, 60),
 ('H&R P C SPECIAL SCHEME', 5.125032967275007, 36),
 ('HMR BARDOC OOH', 4.962091311252586, 321),
 ('DARWEN HEALTHCARE', 4.954095807373403, 1917),
 ('INTEGRATED CARE 24 LTD (CWSX OOH)', 4.892374195851049, 426),
 ('THE LIMES MEDICAL PRACTICE', 4.534452381671439, 1321),
 ('IC24 LTD (BRIGHTON & HOVE OOH)', 4.3382100812948154, 357),
 ('OLDHAM 7 DAY ACCESS HUB2 OOH', 4.313726724643943, 56),
 ('IC24 LTD (NORFOLK & WISBECH OOH)', 4.260985551001909, 489),
 ('ROSSENDALE MIU & OOH', 4.258410699487984, 18),
 ('BURY WALK-IN CENTRE', 4.152942664215405, 138),
 ('IC24 LTD (HORSHAM & MID SUSSEX OOH)', 3.7841863697802585, 215),
 ('LCW HOUNSLOW CCG OOH', 3.5846850269075774, 69),
 ('WEEKEND WORKING EASINGTON NORTH', 3.5686610126605642, 278),
 ('COMPASS ENFIELD', 3.559947987224374, 7),
 ('BASSETLAW DRUG & ALCOHOL SERVICE', 3.534354014906708, 2),
 ('THE PARK SURGERY', 3.515360526768244, 969),
 ('CHAPEL STREET SURGERY', 3.488513740905188, 1504),
 ('BEECHWOOD MEDICAL PRACTICE', 3.472783478378863, 1552),
 ('BASSETLAW HOSPICE OF THE GOOD SHEPHERD', 3.456063571231854, 46),
 ('CARDEN SURGERY', 3.455174292983251, 1375),
 ('GP IN A&E (WIC)', 3.3978131408148813, 87),
 ('NORTHAMPTONSHIRE OOH SERVICE', 3.3965412266669794, 382),
 ('WORDEN MEDICAL CENTRE', 3.3406704393154545, 1898),
 ('BRISDOC HEALTHCARE SERVICES OOH', 3.337061645021116, 566),
 ('BURY OOH', 3.324230940753404, 292),
 ('IC24 SOUTHEND/CP&R CCG OOH', 3.2239221883539257, 336),
 ('IC24 LTD (CRAWLEY OOH)', 3.196512931845654, 173),
 ('EASTBOURNE  HAILSHAM & SEAFORD OOH', 2.9921865871245084, 255),
 ('THE ROSEBERRY PRACTICE', 2.9780902639165365, 1450),
 ('SHAFTESBURY MEDICAL CTR.', 2.8991880742491705, 2126),
 ('THE RICHMOND HILL PRACTICE', 2.85280835225292, 1729),
 ('DGS OOH (INTEGRATED CARE 24 LTD)', 2.7983127436197703, 325),
 ('THE LAKESIDE PRACTICE', 2.7850580931805404, 1554),
 ('DEWSBURY MSK SERVICE', 2.7745661142711002, 3),
 ('BRISDOC HEALTHCARE SERVICES OOH', 2.723659563372342, 74),
 ('HALLIWELL SURGERY 1', 2.678256242758091, 1124),
 ('THE ROYTON & CROMPTON FAMILY PRACTICE', 2.6618484685948243, 2054),
 ('PRACTICE 3  MEDICAL CENTRE  BRIDLINGTON', 2.652303090532112, 1936),
 ('LCWUCC - IUC NCL', 2.595722179935655, 443),
 ('THE CREST FAMILY PRACTICE', 2.4988492604750943, 1294),
 ('DR MOKASHI', 2.4872173488969644, 1341),
 ('PERKINS PRACTICE', 2.474243799075293, 899),
 ('DARLASTON HEALTH CENTRE', 2.4496428330996367, 996),
 ("DR MA SIMS' PRACTICE", 2.4309510122755604, 1857),
 ('1/LOWER BROUGHTON MEDICAL PRACTICE', 2.4231560912317156, 1044),
 ('CORNWALLIS PLAZA SURGERY', 2.4199093225127037, 2326),
 ('FAIRMORE MEDICAL PRACTICE', 2.372441338492957, 1288),
 ('LAWLEY MEDICAL PRACTICE', 2.3645825391738007, 1409),
 ("PEEL GP'S", 2.345641501084622, 1557),
 ('EASTLANDS MEDICAL CENTRE', 2.3230485063291466, 1369),
 ('MAGHULL HEALTH CENTRE (DR SAPRE)', 2.3168420912562087, 1322),
 ('INTEGRATED CARE 24 LIMITED OOH', 2.313669433658373, 511),
 ('IC24 LTD (HWLH OOH)', 2.297074430930294, 216),
 ('CHADWICK PRACTICE', 2.290291691028607, 1568),
 ('WILLOW BANK SURGERY', 2.284247125557156, 1934),
 ('C&WPT OOH SERVICE', 2.273421069837655, 341),
 ('THE MERRYWOOD PRACTICE', 2.2602612741094434, 1234),
 ('LEYLAND SURGERY', 2.2560788720197227, 1213),
 ('WALKDEN MEDICAL PRACTICE', 2.246395094348847, 1577),
 ('RADCLIFFE MEDICAL PRACTICE', 2.238066209002983, 1553),
 ('RIBBLESDALE GP-DR SUBBIAH', 2.198248907972802, 1100),
 ('THE MAZHARI & KHAN PRACTICE', 2.1956746320322487, 912),
 ('JAMES ALEXANDER FAMILY PRACTICE', 2.1893766946111715, 1634),
 ('B&H INTERMEDIATE CARE SERVICE', 2.1890666499277667, 456),
 ('HARDEN SURGERY', 2.152547430238374, 1228),
 ('THE GATEWAY MEDICAL PRACTICE', 2.1520641346076577, 1349),
 ('QUAYSIDE MEDICAL PRACTICE', 2.151508280605607, 1422),
 ('FISHPONDS FAMILY PRACTICE', 2.0792092877784474, 1632),
 ('HASTINGS AND ROTHER OOH', 2.078858201573084, 291),
 ("ST MARY'S SURGERY", 2.044901866222211, 981),
 ('DRS CLOAK  CHOI AND MILLIGAN', 2.044082750596381, 1661),
 ('THE THORNTON PRACTICE', 1.9915642762571337, 1970),
 ('IC24 LTD (EAST SURREY OOH)', 1.9550613103176373, 194),
 ('CORNISHWAY GROUP PRACTICE', 1.9512918247018656, 1506),
 ('PREMIER HEALTH TEAM', 1.937931370947089, 876),
 ('CONCORD MEDICAL PRACTICE', 1.925308881273335, 1386),
 ('COULBY MEDICAL PRACTICE', 1.919457444638258, 1585),
 ('PARKSIDE MEDICAL CENTRE', 1.9143777559258415, 1314),
 ('THE DISCOVERY PRACTICE', 1.9021514653848708, 1268),
 ('ANCORA MEDICAL PRACTICE', 1.881515873122155, 2347),
 ('DARWEN HEALTHLINK', 1.8771229548535704, 2019),
 ('ROOLEY LANE MED. CENTRE', 1.8620670729731688, 1522),
 ('JALAL PRACTICE', 1.8526341043113717, 885),
 ('GREAT HOMER STREET MEDICAL CENTRE', 1.8017358680623603, 1062),
 ('THE CRESCENT SURGERY', 1.7981624968168801, 1734),
 ('BROOKVALE PRACTICE', 1.796309950118724, 1484),
 ('NORTHPOINT', 1.791921652617503, 1137),
 ('LEIGH NHS WIC', 1.7778364333949126, 162),
 ('DR SP SINGH AND PARTNERS', 1.766175319780631, 1840),
 ('BELGRAVE SURGERY', 1.7619383226319991, 1291),
 ('THE PARKS MEDICAL PRACTICE', 1.7572804146410668, 1466),
 ('THE ROSS PRACTICE', 1.716359708431743, 1648),
 ('THOMAS WALKER', 1.6949011707903539, 1377),
 ('OAKFIELD MEDICAL PRACTICE', 1.6912044353921025, 1055),
 ("DR DP CHARLES' PRACTICE", 1.6891933985903518, 1353),
 ('BOWLING HALL MED PRACTICE', 1.6885690432193319, 1352),
 ('NORTHGATE VILLAGE SURGERY', 1.6838489125165406, 1304)]

In [141]:
# unique_practices = ...
anomalies = [("NATIONAL ENHANCED SERVICE", 11.6958178629, 7)] * 100

In [52]:
grader.score.dw__script_anomalies(anomalies)

==================
Your score:  0.4400000000000002
==================

In [35]:
scripts = pd.read_csv('./dw-data/201701scripts_sample.csv.gz', compression='gzip')
opioids = ['morphine', 'oxycodone', 'methadone', 'fentanyl', 'pethidine', 'buprenorphine', 'propoxyphene', 'codeine']

ops = '|'.join(opioids)

bnf_by_practice = scripts.groupby('practice').agg({'bnf_code': 'count'}).rename(columns={'bnf_code':'bnf_sum'})


scripts_chem = pd.merge(scripts, chem, left_on='bnf_code', right_on='CHEM SUB', how='left', sort=False)
scripts_chem['opioid?'] = (scripts_chem['NAME'].str.contains(ops, case=False) | scripts_chem['bnf_name'].str.contains(ops, case=False))

opioids_per_practice = scripts_chem.groupby('practice')['opioid?'].mean()
overall_opioids_rate = scripts_chem['opioid?'].mean()

standard_error_per_practice = overall_opioids_std / np.sqrt(bnf_by_practice.bnf_sum)

opioid_scores = (relative_opioids_per_practice / standard_error_per_practice).reset_index(name='opioid_scores')

relative_opioids_per_practice = opioids_per_practice - overall_opioids_rate

overall_opioids_std = scripts_chem['opioid?'].std()

unique_practices = practices.sort_values(by='name').groupby('code', sort=False).first()
unique_practices.reset_index(inplace=True)

final_merge = opioid_scores.merge(unique_practices[['code','name']], left_on='practice',
                                  right_on='code', how='left')

results = final_merge.merge(bnf_by_practice.reset_index(), on='practice')

subset = results[['name', 'opioid_scores', 'bnf_sum']]
anomalies = [tuple(val) for val in subset.values]
anomalies = sorted(anomalies, key=lambda x: x[1], reverse=True)[:100]

In [40]:
opioids_per_practice

practice
A81005    0.005964
A81007    0.010989
A81011    0.012747
A81012    0.009002
A81017    0.012552
            ...
Y05570    0.000000
Y05583    0.000000
Y05597    0.000000
Y05660    0.000000
Y05670    0.000000
Name: opioid?, Length: 856, dtype: float64

In [41]:
# opioids_per_practice,
overall_opioids_rate, overall_opioids_std

(0.03578300017453619, 0.1857487886805953)

In [37]:
grader.score.dw__script_anomalies(anomalies)

==================
Your score:  0.9900000000000007
==================

## Question 5: script_growth

Another way to identify anomalies is by comparing current data to historical data. In the case of identifying sites of drug abuse, we might compare a practice's current rate of opioid prescription to their rate 5 or 10 years ago. Unless the nature of the practice has changed, the profile of drugs they prescribe should be relatively stable. We might also want to identify trends through time for business reasons, identifying drugs that are gaining market share. That's what we'll do in this question.

We'll load in beneficiary data from 6 months earlier, June 2016, and calculate the percent growth in prescription rate from June 2016 to January 2017 for each `bnf_name`. We'll return the 50 items with largest growth and the 50 items with the largest shrinkage (i.e. negative percent growth) as a list of tuples sorted by growth rate in descending order in the format `(script_name, growth_rate, raw_2016_count)`. You'll notice that many of the 50 fastest growing items have low counts of prescriptions in 2016. Filter out any items that were prescribed less than 50 times.

In [11]:
practices.head(2)

,code,name,addr_1,addr_2,borough,village,post_code
0,A81001,THE DENSHAM SURGERY,THE HEALTH CENTRE,LAWSON STREET,STOCKTON ON TEES,CLEVELAND,TS18 1HU
1,A81002,QUEENS PARK MEDICAL CENTRE,QUEENS PARK MEDICAL CTR,FARRER STREET,STOCKTON ON TEES,CLEVELAND,TS18 2AW

In [10]:
scripts.head()

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity
0,N85639,0106020C0,Bisacodyl_Tab E/C 5mg,1,0.39,0.47,12
1,N85639,0106040M0,Movicol Plain_Paed Pdr Sach 6.9g,1,4.38,4.07,30
2,N85639,0301011R0,Salbutamol_Inha 100mcg (200 D) CFF,1,1.50,1.40,1
3,N85639,0304010G0,Chlorphenamine Mal_Oral Soln 2mg/5ml,1,2.62,2.44,150
4,N85639,0401020K0,Diazepam_Tab 2mg,1,0.16,0.26,6

In [17]:
scripts_now = scripts.groupby('bnf_name').agg({'bnf_name':'count'}).rename(columns = {'bnf_name':'bnf_count_now'}).reset_index()

In [18]:
scripts_now.head()

                                   bnf_name  bnf_count_now
0    365 Film 10cm x 12cm VP Adh Film Dress              1
1  365 Non Adherent 10cm x 10cm Pfa Plas Fa              3
2  365 Non Adherent 10cm x 20cm Pfa Plas Fa              1
3  365 Non Woven Island 8cm x 10cm Adh Dres              1
4  365 Transpt Island 5cm x 7.2cm VP Adh Fi              2

In [14]:
scripts16 = pd.read_csv('./dw-data/201606scripts_sample.csv.gz')
scripts16.head(4)

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity
0,N85638,0301011R0,Salamol_Inha 100mcg (200 D) CFF (Teva),2,2.92,2.73,2
1,N85638,0301011R0,Easyhaler_Salbutamol Sulf 200mcg (200D),1,6.63,6.15,1
2,N85638,0301020I0,Ipratrop Brom_Inh Soln 500mcg/2ml Ud,1,1.77,1.75,12
3,N85638,0301020I0,Ipratrop Brom_Inh Soln 250mcg/1ml Ud,1,4.47,4.15,20

In [20]:
scripts_16 = scripts16.groupby('bnf_name').agg({'bnf_name':'count'})\
.rename(columns = {'bnf_name':'bnf_count_16'}).reset_index()
scripts_16.head()

                                   bnf_name  bnf_count_16
0    365 Film 15cm x 20cm VP Adh Film Dress             1
1      365 Film 4cm x 5cm VP Adh Film Dress             1
2  365 Non Adherent 10cm x 10cm Pfa Plas Fa             3
3  365 Non Woven Island 10cm x 10cm Adh Dre             1
4  365 Non Woven Island 10cm x 15cm Adh Dre             1

In [54]:
scripts_compare = scripts_now.merge(scripts_16, left_on = 'bnf_name',\
                                    right_on = 'bnf_name', how = 'inner').reset_index()
# filter out any items that were prescribed less than 50 times.
scripts_compare = scripts_compare[scripts_compare['bnf_count_16'] >= 50]
scripts_compare['rate'] = (scripts_compare.bnf_count_now - scripts_compare.bnf_count_16) /\
scripts_compare.bnf_count_16

scripts_compare = scripts_compare.sort_values('rate',ascending=False).reset_index()[['bnf_name','bnf_count_now','bnf_count_16',\
                                                                                     'rate']]

In [55]:
scripts_compare.head(10)

,bnf_name,bnf_count_now,bnf_count_16,rate
0,Butec_Transdermal Patch 5mcg/hr,277,62,3.467742
1,Butec_Transdermal Patch 10mcg/hr,276,69,3.000000
2,Fostair NEXThaler_Inh 200mcg/6mcg (120D),209,86,1.430233
3,Pneumococcal_Vac 0.5ml Vl (23 Valent),438,193,1.269430
4,Spiolto Respimat_Inha2.5/2.5mcg(60D)+Dev,118,52,1.269231
5,Trulicity_Inj 1.5mg/0.5ml Pf Pen,118,54,1.185185
6,CosmoCol_Paed Oral Pdr Sach 6.9g,135,62,1.177419
7,Dulaglutide_Inj 1.5mg/0.5ml Pf Dev,161,82,0.963415
8,ViATIM_Vac D/Chamber 160u/25mcg 1ml Pfs,239,125,0.912000
9,Empagliflozin_Tab 25mg,237,125,0.896000

In [56]:
scripts_compare.tail(10)

,bnf_name,bnf_count_now,bnf_count_16,rate
3475,Sunsense_Sunsensitive Crm SPF 50+,22,153,-0.856209
3476,Hepatyrix_Vac 1440u/25mcg/ml 1ml Pfs,27,216,-0.875000
3477,Climagest_Tab 2mg,7,66,-0.893939
3478,Climaval_Tab 2mg,13,132,-0.901515
3479,Orphenadrine HCl_Tab 50mg,9,102,-0.911765
3480,Hydroxyzine HCl_Oral Soln 10mg/5ml,8,94,-0.914894
3481,Ovysmen_Tab,5,67,-0.925373
3482,Climaval_Tab 1mg,10,136,-0.926471
3483,Climesse_Tab,4,69,-0.942029
3484,Polyalc_Eye Dps 1.4%,1,272,-0.996324

In [61]:
# solution1: use data structure
script_growth =[] 
for i in range(50):
    script_growth.append((scripts_compare['bnf_name'][i], scripts_compare['rate'][i],\
                               scripts_compare['bnf_count_16'][i]))
for i in range(50):
    script_growth.append((scripts_compare.tail(50).reset_index()['bnf_name'][i], scripts_compare.tail(50).reset_index()['rate'][i],\
                               scripts_compare.tail(50).reset_index()['bnf_count_16'][i]))

In [57]:
# solution2: use intertuples
# col_l = ['bnf_name','rate','bnf_count_16']
                                                                                     
# script_growth = list(pd.concat([scripts_compare.head(50)[col_l],\
#                                 scripts_compare.tail(50)[col_l]]).itertuples(index=False, name=None))

In [58]:
len(script_growth)

100

In [59]:
script_growth

[('Butec_Transdermal Patch 5mcg/hr', 3.467741935483871, 62),
 ('Butec_Transdermal Patch 10mcg/hr', 3.0, 69),
 ('Fostair NEXThaler_Inh 200mcg/6mcg (120D)', 1.430232558139535, 86),
 ('Pneumococcal_Vac 0.5ml Vl (23 Valent)', 1.2694300518134716, 193),
 ('Spiolto Respimat_Inha2.5/2.5mcg(60D)+Dev', 1.2692307692307692, 52),
 ('Trulicity_Inj 1.5mg/0.5ml Pf Pen', 1.1851851851851851, 54),
 ('CosmoCol_Paed Oral Pdr Sach 6.9g', 1.1774193548387097, 62),
 ('Dulaglutide_Inj 1.5mg/0.5ml Pf Dev', 0.9634146341463414, 82),
 ('ViATIM_Vac D/Chamber 160u/25mcg 1ml Pfs', 0.912, 125),
 ('Empagliflozin_Tab 25mg', 0.896, 125),
 ('CareSens Lancets 0.31mm/30 Gauge', 0.8955223880597015, 67),
 ('Fostair_Inh 200mcg/6mcg (120D) CFF', 0.8616600790513834, 253),
 ('Orbis Nor Saline Sod Chlor 0.9% Nsl Dps', 0.8588235294117647, 85),
 ('Umeclidinium Brom_Inh 65mcg (30D)', 0.8275862068965517, 87),
 ('Ultibro Breezhaler_Pdr Inh Cap + Dev', 0.8016528925619835, 121),
 ('Medihoney_Barrier Crm', 0.7840909090909091, 88),
 ('Fluoxetine HCl_Oral Soln 20mg/5ml S/F', 0.7808219178082192, 73),
 ('TEE2 (Reagent)_Strips', 0.7777777777777778, 81),
 ('Zaluron XL_Tab 400mg', 0.7586206896551724, 58),
 ('Laxido_Paed Plain Oral Pdr Sach 6.9g', 0.7586206896551724, 174),
 ('Prednisolone_Oral Soln 5mg/5ml Ud', 0.726027397260274, 73),
 ('Buprenorphine_Patch 15mcg/hr (7day)', 0.7155963302752294, 109),
 ('Coloplast_SenSura Mio Maxi Drnbl Bag S/C', 0.7037037037037037, 81),
 ('Octenisan_Antimicrobial Wsh Lot', 0.7027027027027027, 74),
 ('Duaklir Genuair_340mcg/12mcg (60D)', 0.6710526315789473, 152),
 ('Sod Chlor_Inh Soln 0.9% 2.5ml Ud Amp', 0.6419753086419753, 162),
 ('Coloplast_SenSura Mio Maxi Drnbl Bag L/C', 0.6274509803921569, 51),
 ('Flutiform_Inha 50/5mcg (120 D)', 0.625, 88),
 ('Ins Degludec_100u/ml 3ml Pf Pen', 0.6166666666666667, 60),
 ('CareSens Lancets 0.36mm/28 Gauge', 0.6111111111111112, 90),
 ('Epimax Crm 500g', 0.61, 100),
 ('Evacal D3_Tab Chble 400u/1.5g', 0.6046511627906976, 86),
 ('Shortec_Cap 20mg', 0.6029411764705882, 68),
 ('Co-Trimoxazole_Oral Susp 40/200mg/5mlS/F', 0.6, 50),
 ('Ciprofloxacin_Gran For Susp 250mg/5ml', 0.5921052631578947, 76),
 ('AgaMatrix Ultra-Thin Lancets 0.35mm/28 G', 0.5660377358490566, 53),
 ('Zemtard 120 XL_Cap 120mg', 0.5636363636363636, 55),
 ('Nutramigen 2 + LGG_Pdr', 0.5604395604395604, 91),
 ('Toujeo_300u/ml 1.5ml Pf SoloStar Pen', 0.5408805031446541, 159),
 ('Ins Tresiba_FlexTouch 100u/ml 3ml Pf Pen', 0.5405405405405406, 148),
 ('Longtec_Tab 30mg M/R', 0.5370370370370371, 108),
 ('Adalat_Cap 5mg', 0.5365853658536586, 82),
 ('Dexameth_Oral Soln 2mg/5ml S/F', 0.5294117647058824, 68),
 ('Haloperidol_Inj 5mg/ml 1ml Amp', 0.5288461538461539, 104),
 ('Lyclear_Dermal Crm 5%', 0.5211267605633803, 71),
 ('Valupak_Multivit & Mineral Tab OAD', 0.5098039215686274, 51),
 ('Coloplast_Sensura Mio Maxi Clsd Bag + Fl', 0.5056179775280899, 89),
 ('Medikinet XL_Cap 10mg', 0.48484848484848486, 99),
 ('Dovobet_Gel Applic', 0.48148148148148145, 54),
 ('Incruse Ellipta_Inh 55mcg (30D)', 0.4807692307692308, 208),
 ('Oxycodone HCl_Tab 20mg M/R', -0.4318181818181818, 264),
 ('Cardura XL_Tab 4mg', -0.43478260869565216, 69),
 ('Oxycodone HCl_Tab 80mg M/R', -0.4358974358974359, 78),
 ('Verapamil HCl_Cap 120mg M/R', -0.43790849673202614, 153),
 ('Topamax_Tab 100mg', -0.45161290322580644, 62),
 ('Opticrom_Allergy Eye Dps 2%', -0.4523809523809524, 126),
 ('Optilast_Eye Dps 0.05%', -0.45454545454545453, 55),
 ('Actonel_Once a Week Tab 35mg', -0.4576271186440678, 59),
 ('Premique_Tab 0.625mg/5mg', -0.47039473684210525, 304),
 ('Sunsense_Daily Face Crm Spf 50+', -0.48344370860927155, 151),
 ('Hydrocort/Crotamiton_Crm 0.25%/10%', -0.48936170212765956, 141),
 ('Azelastine HCl_Aq Eye Dps 0.05%', -0.5036231884057971, 276),
 ('Opticrom_Eye Dps 2% (Aq)', -0.5073891625615764, 203),
 ('Metoprolol Tart_Tab 200mg M/R', -0.509090909090909, 55),
 ('Rapitil_Eye Dps 2%', -0.5096774193548387, 155),
 ('Desloratadine_Oral Soln 2.5mg/5ml S/F', -0.5147058823529411, 136),
 ('Erythromycin_Ethylsuc Tab 500mg', -0.5154639175257731, 97),
 ('Aquacel Foam Adhesive 8cm x 8cm Wound Dr', -0.5294117647058824, 68),
 ('Zirtek_Allergy Tab 10mg', -0.5303030303030303, 66),
 ('Antaz Sulf/Xylomet_Eye Dps 0.5%/0.05%', -0.5454545454545454, 66),
 ('Vital 1.5kcal_Liq (Vanilla)', -0.5466666666666666, 75),
 ('Oxybutynin HCl_Oral Soln 2.5mg/5ml S/F', -0.5573770491803278, 61),
 ('Prazosin HCl_Tab 500mcg', -0.5581395348837209, 86),
 ('Artificial Saliva_Spy 50ml', -0.5586854460093896, 213),
 ('Sunsense_Ultra Lot Spf 50+', -0.5652173913043478, 368),
 ('Telfast 120_Tab 120mg', -0.5698924731182796, 93),
 ('Otrivine-Antistin_Eye Dps', -0.572463768115942, 138),
 ('Fexofenadine HCl_Tab 30mg', -0.5959595959595959, 297),
 ('Mag Trisil_Mix', -0.6119402985074627, 67),
 ('Glibenclamide_Tab 5mg', -0.6164383561643836, 146),
 ('Co-Danthrusate_Cap 50mg/60mg', -0.6296296296296297, 81),
 ('Ketotifen Fumar_Eye Dps 250mcg/ml', -0.6842105263157895, 57),
 ('Uvistat_Sun Crm Spf 50', -0.6917293233082706, 133),
 ('Haelan_Tape 7.5cm x 50cm', -0.7130434782608696, 115),
 ('Haelan_Tape 7.5cm x 20cm', -0.72, 100),
 ('Beconase_Hayfever Nsl Spy 50mcg (180 D)', -0.7384615384615385, 65),
 ('Uvistat_Sun Crm Spf 30', -0.7647058823529411, 68),
 ('Deep Freeze_Cold Gel 2%', -0.7758620689655172, 58),
 ('Adizem-SR_Tab 120mg', -0.8269230769230769, 52),
 ('Anugesic HC_Crm', -0.8541666666666666, 96),
 ('Sunsense_Sunsensitive Crm SPF 50+', -0.8562091503267973, 153),
 ('Hepatyrix_Vac 1440u/25mcg/ml 1ml Pfs', -0.875, 216),
 ('Climagest_Tab 2mg', -0.8939393939393939, 66),
 ('Climaval_Tab 2mg', -0.9015151515151515, 132),
 ('Orphenadrine HCl_Tab 50mg', -0.9117647058823529, 102),
 ('Hydroxyzine HCl_Oral Soln 10mg/5ml', -0.9148936170212766, 94),
 ('Ovysmen_Tab', -0.9253731343283582, 67),
 ('Climaval_Tab 1mg', -0.9264705882352942, 136),
 ('Climesse_Tab', -0.9420289855072463, 69),
 ('Polyalc_Eye Dps 1.4%', -0.9963235294117647, 272)]

In [62]:
# script_growth = [("Butec_Transdermal Patch 5mcg\/hr", 3.4677419355, 62.0)] * 100

In [63]:
grader.score.dw__script_growth(script_growth)

==================
Your score:  1.0
==================

## Question 6: rare_scripts

Does a practice's prescription costs originate from routine care or from reliance on rarely prescribed treatments? Commonplace treatments can carry lower costs than rare treatments because of efficiencies in large-scale production. While some specialist practices can't help but avoid prescribing rare medicines because there are no alternatives, some practices may be prescribing an unnecessary amount of brand-name products when generics are available. Let's identify practices whose costs disproportionately originate from rarely prescribed items.

First we have to identify which `'bnf_code'` are rare. To do this, find the probability $p$ of a prescription having a particular `'bnf_code'` if the `'bnf_code'` was randomly chosen from the unique options in the beneficiary data. We will call a `'bnf_code'` rare if it is prescribed at a rate less than $0.1p$.

In [75]:
scripts.bnf_code.nunique()

1975

In [78]:
scripts['bnf_code'].value_counts() / len(scripts)

0906040G0    0.014840
090402000    0.011016
0302000N0    0.010214
130201000    0.008839
0601060D0    0.008799
               ...
220560505    0.000001
224041040    0.000001
1001022Y0    0.000001
0603020F0    0.000001
229038990    0.000001
Name: bnf_code, Length: 1975, dtype: float64

In [82]:
p = 1/scripts.bnf_code.nunique()
rates = scripts['bnf_code'].value_counts() / len(scripts)

rare_codes = rates [rates < 0.1 * p].index.unique()
scripts['rare'] = scripts['bnf_code'].isin(rare_codes)

Now for each practice, calculate the proportion of costs that originate from prescription of rare treatments (i.e. rare `'bnf_code'`). Use the `'act_cost'` field for this calculation.

In [83]:
scripts.head(1)

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity,rare
0,N85639,0106020C0,Bisacodyl_Tab E/C 5mg,1,0.39,0.47,12,False

In [90]:
rare_cost_prop = (scripts[scripts['rare']].groupby('practice')['act_cost'].sum().fillna(0)/scripts.groupby('practice')['act_cost'].sum())

In [91]:
rare_cost_prop

practice
A81005    0.012017
A81007    0.008381
A81011    0.005116
A81012    0.013747
A81017    0.007359
            ...
Y05570         NaN
Y05583         NaN
Y05597         NaN
Y05660    0.000323
Y05670         NaN
Name: act_cost, Length: 856, dtype: float64

In [92]:
# rare_cost_prop = (scripts[scripts['rare']].groupby('practice')['act_cost'].sum()\
#                   /scripts.groupby('practice')['act_cost'].sum()).fillna(0)

Now we will calculate a z-score for each practice based on this proportion.
First take the difference of `rare_cost_prop` and the proportion of costs originating from rare treatments across all practices.

In [93]:
relative_rare_cost_prop = (rare_cost_prop - scripts[scripts['rare']]['act_cost'].sum() /scripts['act_cost'].sum())

Now we will estimate the standard errors (i.e. the denominator of the z-score) by simply taking the standard deviation of this difference.

In [96]:
standard_errors = relative_rare_cost_prop.std()

Finally compute the z-scores. Return the practices with the top 100 z-scores in the form `(post_code, practice_name, z-score)`. Note that some practice codes will correspond with multiple names. In this case, use the first match when sorting names alphabetically.

In [102]:
rare_scores = relative_rare_cost_prop/standard_errors

In [118]:
rare_scores

practice
A81005   -0.062111
A81007   -0.119342
A81011   -0.170728
A81012   -0.034872
A81017   -0.135420
            ...
Y05570         NaN
Y05583         NaN
Y05597         NaN
Y05660   -0.246167
Y05670         NaN
Name: act_cost, Length: 856, dtype: float64

In [122]:
pd.DataFrame(rare_scores).reset_index().head()

  practice  act_cost
0   A81005 -0.062111
1   A81007 -0.119342
2   A81011 -0.170728
3   A81012 -0.034872
4   A81017 -0.135420

In [113]:
unique_practices = (practices.sort_values(['code','name']).groupby('code')\
                    .first().reset_index())[['code', 'name']]

In [138]:
rare_scripts = unique_practices.merge(pd.DataFrame(rare_scores).reset_index(), left_on = 'code'\
                               ,right_on = 'practice', how = 'left')\
[['code','name','act_cost']].sort_values('act_cost', ascending = False)

In [139]:
rare_scripts = list(rare_scripts.head(100).itertuples(index =None, name=None))

In [140]:
rare_scripts

[('Y03472', 'CONSULTANT DIABETES TEAM', 15.488406625215609),
 ('Y05320', 'DMC COMMUNITY DERMATOLOGY RBWF', 14.408360263244049),
 ('Y04404', 'OUTPATIENTS JUBILEE HEALTH CENTRE', 7.183051624616913),
 ('Y03484', 'DMC COMMUNITY DERMATOLOGY CLINIC', 6.94027129350587),
 ('Y04424', 'DMC HEALTHCARE', 6.513021887657125),
 ('Y00631', 'BINGLEY DERMATOLOGY CLINIC', 5.481949563579427),
 ('A89038', 'BARMSTON MEDICAL CENTRE', 5.395227692877738),
 ('Y01696', 'BASSETLAW HOSPICE OF THE GOOD SHEPHERD', 4.086401965874138),
 ('Y03699', 'OLDHAM DERMATOLOGY SERVICE', 3.9083612233045373),
 ('Y02045', 'VERNOVA HEALTHCARE CIC', 3.029278875457491),
 ('Y02823', 'DMC VICARAGE LANE', 2.9087122950668833),
 ('Y00997', 'COMMUNITY DERMATOLOGY SERVICE', 2.8744326765475274),
 ('Y05019', 'OLDHAM TOTAL SKIN SERVICE', 2.5950238325625326),
 ('Y01003', 'BURY OOH', 2.2385300542366964),
 ('Y05431', 'NOTTS APPLIANCE MANAGEMENT SERVICE', 1.9401676755986765),
 ('Y03557', 'IPU 10-17 RECOVERY COVENTRY', 1.9337780557880855),
 ('Y05419', 'WEEKEND WORKING EASINGTON NORTH', 1.9075976453613963),
 ('Y05434', 'NOTTS APPLIANCE MANAGEMENT SERVICE', 1.5407899736209778),
 ('L84042', 'LONDON MEDICAL PRACTICE', 1.5276438379006312),
 ('Y04871', 'LEARNING ASSESSMENT & NEUROCARE BURY', 1.3722198959202228),
 ('Y05432', 'NOTTS APPLIANCE MANAGEMENT SERVICE', 1.2430603789392323),
 ('F86057', 'THE WILLOWS PRACTICE', 1.2199688533037305),
 ('L81673', 'BCH DERMATOLOGY SERVICE', 1.2171032677439781),
 ('Y04089', 'VIRGIN CARE (MIDDLESBROUGH)', 1.1481868452872808),
 ('Y03762', 'BASSETLAW HEALTH PARTNERSHIP', 1.0997894858817119),
 ('Y05430', 'NOTTS APPLIANCE MANAGEMENT SERVICE', 1.0693048779455752),
 ('B85030', 'SCRIVINGS CLECKHEATON HLTH CTR', 1.0509636815289396),
 ('P81736', 'WHITEFIELD HEALTHCARE', 1.0418738998166606),
 ('Y00570', 'GP LED DERMATOLOGY SERVICE', 1.001496149473522),
 ('Y04606', 'LANCASTER HOUSE CONTINENCE', 0.9836766439848758),
 ('P81712', 'DARWEN HEALTH CENTRE', 0.9796583738526915),
 ('Y05433', 'NOTTS APPLIANCE MANAGEMENT SERVICE', 0.9788666054047578),
 ('Y02943', 'NEUROLOGY LONG TERM CONDITIONS', 0.9120977204922354),
 ('P84051', 'EASTLANDS MEDICAL CENTRE', 0.8638524048271157),
 ('Y02203', 'DURHAM DALES EAST DERMATOLOGY', 0.8410229946306337),
 ('G82704', 'THE CHURCH VIEW PRACTICE', 0.8274535514990962),
 ('F81070', 'GRAFTON SURGERY', 0.8063271355343021),
 ('Y05435', 'NOTTS APPLIANCE MANAGEMENT SERVICE', 0.7852638328907537),
 ('P82625', 'CHARLOTTE STREET SURGERY', 0.7370021358206574),
 ('P82640', 'AL FAL MEDICAL GROUP', 0.6846684122334249),
 ('F84706', 'DR SKS SWEDAN', 0.6845702258326017),
 ('Y01168', 'COMMUNITY GYNAECOLOGY SERVICE', 0.6479053374582235),
 ('N81080', 'NORTHGATE MEDICAL CENTRE', 0.6344471769451618),
 ('A87022', 'NORTHUMBERLAND PARK MEDICAL GROUP', 0.608321308122247),
 ('B83058', 'THE AVICENNA MEDICAL PRACTICE', 0.5691092133975985),
 ('M85766', 'BALSALL HEATH HEALTH CENTRE (S)', 0.5363331839982968),
 ('G81658', 'THE STATION PRACTICE', 0.5078032948927588),
 ('M85715', 'SOHO ROAD PRIMARY CARE CENTRE', 0.5040299802531903),
 ('E85659', 'DR RK KUKAR  PARKVIEW CTR FOR H&W', 0.4975828802662012),
 ('M85716', "DR KHUROO'S PRACTICE", 0.48164948680936215),
 ('B83067', 'THE SPRINGFIELD SURGERY (BINGLEY)', 0.4776065933008361),
 ('B84011', 'CHURCH LANE SURGERY', 0.4734826845374893),
 ('B83032', 'BRADFORD MOOR PRACTICE', 0.46152954161610066),
 ('Y00469', "DR MA SIMS' PRACTICE", 0.45789900706039705),
 ('H81034', 'MADEIRA MEDICAL', 0.45090494444071844),
 ('A83071', 'THE NEW SEAHAM MEDICAL GROUP', 0.42793824440133227),
 ('P91633', 'GROVE MEDICAL PRACTICE', 0.39515533386583357),
 ('P84032', 'DR MOKASHI', 0.3944045133251927),
 ('F84086', 'DR DRIVER & PARTNERS', 0.39058291612922563),
 ('C83041', 'THE WOODLAND MEDICAL PRACTICE', 0.38227931189341297),
 ('G82162', 'RAINHAM HEALTHY LIVING CENTRE', 0.3751679677645814),
 ('A83051', 'MARLBOROUGH SURGERY', 0.3598388588558007),
 ('C84714', 'SUNRISE MEDICAL PRACTICE (GHATTAORA)', 0.34449318211737373),
 ('B82016', 'EAST PARADE SURGERY', 0.33883171939130746),
 ('C84691', 'HIGHGREEN PRACTICE (KHAN)', 0.32701379588610124),
 ('L82001', 'LANDER MEDICAL PRACTICE', 0.316532868503777),
 ('G84027', 'ELM HOUSE SURGERY', 0.31421268680566483),
 ('Y02957', 'LEWISHAM GP LED HEALTH CENTRE', 0.30891220082649823),
 ('G85095', 'MANOR PLACE SURGERY', 0.30321653280864397),
 ('E82656', 'CASSIO SURGERY - E82656', 0.2951501001725924),
 ('M91017', 'NORTHGATE MEDICAL CENTRE', 0.29428502248422594),
 ('L84008', "ST.GEORGE'S SURGERY", 0.2886265612090039),
 ('P81099', 'DR THM MACKENZIE & PARTNERS', 0.285631945522779),
 ('E85018', "DR SOOD'S PRACTICE", 0.2753473776200519),
 ('Y04951', 'ARDEN HEALTHCARE CENTRE', 0.27500134277938015),
 ('N82051', 'BREEZE HILL - SSP HEALTH LIMITED', 0.2671151957154904),
 ('H81097', 'RIVER WEY MEDICAL PRACTICE', 0.26590061639548956),
 ('C82667', 'THE CHARNWOOD PRACTICE', 0.2573650409799158),
 ('C87622', 'GATEWAY PRIMARY CARE', 0.25377223877616933),
 ('E85723', 'NORTHOLT FAMILY PRACTICE', 0.2526499868183922),
 ('C84013', 'BRIDGEGATE AND TALL TREES PARTNERSHIP', 0.25111582834622836),
 ('E85126', 'GREEN PRACTICE', 0.24972741528173217),
 ('P92024', 'THE CHANDLER SURGERY', 0.24811237617584683),
 ('Y01929', 'TELDOC', 0.24467104568126455),
 ('K82078', 'DR ALLAN AND PARTNERS', 0.24129478791599204),
 ('M85068', 'THE VESEY PRACTICE', 0.2396060051026654),
 ('G85034', 'NEXUS HEALTH GROUP', 0.23601293662536965),
 ('P88023', 'HEALD GREEN HEALTH CENTRE 2', 0.23063866441284706),
 ('M83629', 'DRAYTON ROAD SURGERY', 0.22249341073890616),
 ('M83063', 'NORTON CANES HEALTH CENTRE', 0.22181284015734198),
 ('H81615', 'FARNHAM DENE MEDICAL PRACTICE', 0.22135727440927194),
 ('D81024', 'THOMAS WALKER', 0.21348194803802323),
 ('K83051', 'WEAVERS MEDICAL', 0.211440318812327),
 ('G85134', 'THE LISTER PRIMARY CARE CENTRE', 0.20771800046403371),
 ('Y00278', 'DARLASTON HEALTH CENTRE-KHAN', 0.20217653177218228),
 ('Y02671', 'THE PRACTICE HEART OF HOUNSLOW', 0.19886723545681048),
 ('F84631', 'DR PI ABIOLA', 0.19561198346329434),
 ('B81012', 'DR AP KUMAR', 0.19399271110094568),
 ('C83613', 'CAISTOR HEALTH CENTRE', 0.1938114176223193),
 ('M91614', 'STROUD PRACTICE', 0.19095905723975837)]

In [ ]:
rare_scripts = [("Y03472", "CONSULTANT DIABETES TEAM", 16.2626871247)] * 100

In [141]:
grader.score.dw__rare_scripts(rare_scripts)

==================
Your score:  1.0
==================

*Copyright &copy; 2020 The Data Incubator.  All rights reserved.*